= 手動アップグレード
:page-languages: [en, ja, ko, zh]
:revdate: 2025-12-30
:page-revdate: {revdate}

インストールスクリプトを使用するか、希望するバージョンのバイナリを手動でインストールすることでK3sをアップグレードできます。

[NOTE]
====
アップグレードする際は、まずサーバーノードを1つずつアップグレードし、その後エージェントノードをアップグレードしてください。
====

[#_release_channels]
== リリースチャネル

インストールスクリプトを介して行われるアップグレードや、xref:upgrades/automated.adoc[自動アップグレード]機能を使用することで、異なるリリースチャネルに関連付けることができます。以下のチャネルが利用可能です：

|===
| チャネル | 説明

| 安定版
| （デフォルト）安定版は本番環境に推奨されます。これらのリリースはコミュニティテストの期間を経ています。

| 最新
| 最新は常に、semverの順序規則によって決定された最高の非プレリリースバージョンを指します。これらのリリースはまだコミュニティテストの期間を経ていません。

| v1.33（例）
| 各Kubernetesマイナーバージョンにはリリースチャネルが関連付けられており、サービス終了となったバージョンも含まれます。これらのチャネルは、そのマイナーバージョンで利用可能な最新のリリースを選択しますが、必ずしも安定版リリースではありません。
|===

チャネルの包括的で最新のリストについては、https://update.k3s.io/v1-release/channels[k3sチャネルサービスAPI]を訪問してください。チャネルの動作に関する詳細な技術情報については、https://github.com/rancher/channelserver[channelserverプロジェクト]をご覧ください。

[TIP]
====
K3sの新しいバージョンにアップグレードしようとする際は、https://kubernetes.io/docs/setup/release/version-skew-policy/[Kubernetesバージョンスキューポリシー]が適用されます。アップグレードする際に中間のマイナーバージョンをスキップしないようにしてください。システムアップグレードコントローラー自体は、サポートされていないKubernetesバージョンへの変更を防ぐことはできません。
====


== インストールスクリプトを使用してK3sをアップグレードする

古いバージョンからK3sをアップグレードするには、インストールスクリプトを再実行し、最初に実行したときと同じ設定オプションを使用できます。

[IMPORTANT]
.注意
====
`INSTALL_K3S_EXEC`変数、`K3S_`変数、および末尾のシェル引数はすべて、インストールスクリプトによってsystemdユニットおよび環境ファイルを生成するために使用されます。
インストールスクリプトを最初に実行した際に設定を行った場合でも、再実行時に再度設定しないと、元の値は失われます。

xref:installation/configuration.adoc#_configuration_file[設定ファイル]の内容は、インストールスクリプトによって管理されません。
インストールスクリプトから独立した設定を望む場合は、環境変数や引数をインストールスクリプトに渡すのではなく、設定ファイルを使用するべきです。
====


インストールスクリプトを実行すると、

. 新しいk3sバイナリをダウンロードします。
. インストールスクリプトに渡された引数を反映するようにsystemdユニットまたはopenrc initスクリプトを更新します。
. k3sサービスを再起動します。

[NOTE]
====
K3sが停止しても、Podのコンテナは実行を続けます。インストールスクリプトは、K3sを再起動する前にノードをドレインまたはコーディンすることはありません。ワークロードがAPIサーバーの短時間の停止に敏感な場合は、K3sをアップグレードするためにインストールスクリプトを再実行する前に、https://kubernetes.io/docs/reference/kubectl/generated/kubectl_drain/[ノードをドレインしてコーディンする]ために`kubectl`を使用し、その後ノードのコーディンを解除してください。
====

例えば、現在の安定版リリースにアップグレードするには：

[,sh]
----
curl -sfL https://get.k3s.io | INSTALL_K3S_ARTIFACT_URL=<PRIME-ARTIFACTS-URL>/k3s <EXISTING_K3S_ENV> sh -s - <EXISTING_K3S_ARGS>
----

特定のチャネル（最新など）で新しいバージョンにアップグレードしたい場合は、チャネルを指定できます：

[,sh]
----
curl -sfL https://get.k3s.io | INSTALL_K3S_ARTIFACT_URL=<PRIME-ARTIFACTS-URL>/k3s INSTALL_K3S_CHANNEL=latest <EXISTING_K3S_ENV> sh -s - <EXISTING_K3S_ARGS>
----

特定のバージョンにアップグレードしたい場合は、次のコマンドを実行できます：

[,sh]
----
curl -sfL https://get.k3s.io | INSTALL_K3S_ARTIFACT_URL=<PRIME-ARTIFACTS-URL>/k3s INSTALL_K3S_VERSION=vX.Y.Z+k3s1 <EXISTING_K3S_ENV> sh -s - <EXISTING_K3S_ARGS>
----

[TIP]
====
新しいバージョンのk3sをダウンロードしたいが、起動したくない場合は、`INSTALL_K3S_SKIP_START=true`環境変数を使用できます。
====


== バイナリを使用してK3sをアップグレードする

K3sを手動でアップグレードするには、希望するバージョンのK3sバイナリをダウンロードし、既存のバイナリを新しいものと置き換えることができます。

. https://github.com/k3s-io/k3s/releases[リリース]から希望するK3sバイナリのバージョンをダウンロードしてください。
. ダウンロードしたバイナリを`/usr/local/bin/k3s`（または希望する場所）にコピーしてください。
. k3sまたはk3s-agentサービスを再起動するか、k3sプロセス（バイナリ）を再起動してください。

[NOTE]
====
K3sが停止しても、Podのコンテナは実行を続けます。ポッドをドレインしたりノードをコーデンしたりせずにK3sを再起動することは一般的に安全です。ワークロードが短時間のAPIサーバーの停止に敏感な場合は、K3sを再起動する前に`kubectl`を使用してノードを手動でhttps://kubernetes.io/docs/reference/kubectl/generated/kubectl_drain/[ドレインしてコーデン]し、その後ノードのコーデンを解除してください。
====
