= k3s server
:description: Configure the K3s server using CLI flags or configuration files to set critical options for cluster operation
:revdate: 2026-03-31
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2026-10-09
:page-revdate: {revdate}

In this section, you'll learn how to configure the K3s server.

Note that servers also run an agent, so all of the configuration options listed in the xref:cli/agent.adoc[`k3s agent` documentation] are also supported on servers.

Options are listed on this page as CLI flags, but can also be passed as xref:installation/configuration.adoc#_configuration_file[configuration file] options.

== Critical Configuration Options

The following options must be set to the same value on all servers in the cluster, or on agent nodes where the flag is also supported.
Failure to do so may result in unexpected behavior, or node and cluster failure.

|===
| Flag | Environment Variable | Default | Description

| `--cluster-cidr` value
| `K3S_CLUSTER_CIDR`
| "10.42.0.0/16"
| Network CIDR to use for pod IPs

| `--service-cidr` value
| `K3S_SERVICE_CIDR`
| "10.43.0.0/16"
| Network CIDR to use for services IPs

| `--cluster-dns` value
| `K3S_CLUSTER_DNS`
| "10.43.0.10"
| IPv4 Cluster IP for coredns service. Should be in your service-cidr range

| `--cluster-domain` value
| `K3S_CLUSTER_DOMAIN`
| "cluster.local"
| Cluster Domain

| `--flannel-backend` value
| `K3S_FLANNEL_BACKEND`
| "vxlan"
| One of 'none', 'vxlan', 'host-gw', 'wireguard-native'

| `--token` value, `-t` value
| `K3S_TOKEN`
|
| Shared secret used to join a server or agent to a cluster

| `--secrets-encryption`
|
| false
| Enable secret encryption at rest
|===

[#_certificate_authority_ca_flags]
=== Certificate Authority (CA) Flags

|===
| Flag | Environment Variable | Default | Description

| `--cluster-init`
| `K3S_CLUSTER_INIT`
| false
| Initialize a new cluster using embedded etcd

| `--etcd-expose-metrics`
|
| false
| Expose etcd metrics to client interface

| `--etcd-disable-snapshots`
|
| false
| Disable automatic etcd snapshots

| `--etcd-snapshot-name` value
|
| "etcd-snapshot-<unix-timestamp>"
| Set the base name of etcd snapshots.

| `--etcd-snapshot-schedule-cron` value
|
| "0 */12 * * *"
| Snapshot interval time in cron spec. eg. every 5 hours '0 */5 _ * _'

| `--etcd-snapshot-retention` value
|
| 5
| Number of local snapshots to retain on each server node

| `--etcd-snapshot-dir` value
|
| $\{data-dir}/db/snapshots
| Directory to save db snapshots
|===

[#_s3_etcd_snapshot_storage]
=== S3 etcd Snapshot Storage

|===
| Flag | Environment Variable | Default | Description

| `--etcd-s3`
|
|
| Enable backup to S3

| `--etcd-s3-endpoint` value
|
| "s3.amazonaws.com"
| S3 endpoint url

| `--etcd-s3-endpoint-ca` value
|
|
| S3 custom CA cert to connect to S3 endpoint

| `--etcd-s3-skip-ssl-verify`
|
|
| Disables S3 SSL certificate validation

| `--etcd-s3-access-key` value
| `AWS_ACCESS_KEY_ID`
|
| S3 access key

| `--etcd-s3-secret-key` value
| `AWS_SECRET_ACCESS_KEY`
|
| S3 secret key

| `--etcd-s3-session-token` value
| `AWS_SESSION_TOKEN`
|
| S3 session token

| `--etcd-s3-bucket` value
|
|
| S3 bucket name

| `--etcd-s3-bucket-lookup-type` value
|
|
| S3 bucket lookup type, one of 'auto', 'dns', 'path'; default is 'auto' if not set

| `--etcd-s3-region` value
|
| "us-east-1"
| S3 region / bucket location (optional)

| `--etcd-s3-folder` value
|
|
| S3 folder

| `--etcd-s3-retention` value
|
| 5
| Number of S3 snapshots to retain in the configured region, bucket, and prefix

| `--etcd-s3-proxy`
|
|
| Proxy server to use when connecting to S3, overriding any proxy-related environment variables

| `--etcd-s3-config-secret`
|
|
| Name of secret in the kube-system namespace used to configure S3, if etcd-s3 is enabled and no other etcd-s3 options are set


| `--etcd-s3-insecure`
|
|
| Disables S3 over HTTPS

| `--etcd-s3-timeout` value
|
| 5m0s
| S3 timeout
|===

== Deprecated Options

|===
| Flag | Environment Variable | Description

| `--no-flannel`
|
| Use `--flannel-backend=none`

| `--cluster-secret` value
| `K3S_CLUSTER_SECRET`
| Use `--token`
|===

== Logging

|===
| Flag | Environment Variable | Default | Description

| `-v` value
|
| 0
| Number for the log level verbosity

| `--vmodule` value
|
|
| Comma-separated list of pattern=N settings for file-filtered logging

| `--log` value, `-l` value
|
|
| Log to file

| `--alsologtostderr`
|
|
| Log to standard error as well as file (if set)
|===

== Listen Options

|===
| Flag | Environment Variable | Default | Description

| `--bind-address` value
|
| 0.0.0.0
| k3s bind address

| `--https-listen-port` value
|
| 6443
| HTTPS listen port

| `--advertise-address` value
|
| node IPv4 address
| IPv4 address that apiserver uses to advertise to members of the cluster

| `--advertise-port` value
|
| 0
| Port that apiserver uses to advertise to members of the cluster (default: listen port)

| `--tls-san` value
|
|
| Add additional hostname or IPv4/IPv6 addresses as Subject Alternative Name on the server TLS cert

| `--tls-san-security`
|
| true
| Protect the server TLS cert by refusing to add Subject Alternative Names not associated with the kubernetes cluster or the machine itself
|===

== Data Options

|===
| Flag | Environment Variable | Default | Description

| `--data-dir` value, `-d` value
| `K3S_DATA_DIR`
| `/var/lib/rancher/k3s` or `${HOME}/.rancher/k3s` if not root
| Folder to hold state
|===

== Secrets Encryption

|===
| Flag | Environment Variable | Default | Description

| `--secrets-encryption`
|
| false
| Enable secret encryption at rest

| `--secrets-encryption-config-file` value
|
|
| Custom secret encryption configuration file
|===

== Server Options

|===
| Flag | Environment Variable | Default | Description

| `--cluster-init`
| `K3S_CLUSTER_INIT`
| false
| Initialize a new cluster using embedded etcd

| `--cluster-reset`
| `K3S_CLUSTER_RESET`
| false
| Forget all peers and become a single-member cluster

| `--cluster-reset-restore-path` value
|
|
| Path to snapshot file to be restored
|===

== Agent Options

|===
| Flag | Environment Variable | Default | Description

| `--write-kubeconfig` value, `-o` value
| `K3S_KUBECONFIG_OUTPUT`
| `/etc/rancher/k3s/k3s.yaml`
| Write kubeconfig that can be used to connect to the cluster to this path

| `--write-kubeconfig-mode` value
| `K3S_KUBECONFIG_MODE`
| 600
| Write kubeconfig with this mode

| `--server` value, `-s` value
| `K3S_URL`
|
| Server to connect to, used to join a cluster

| `--token` value, `-t` value
| `K3S_TOKEN`
|
| Shared secret used to join a server or agent to a cluster

| `--agent-token` value
| `K3S_AGENT_TOKEN`
|
| Shared secret used to join agents to the cluster, but not servers
|===

== Common Options

|===
| Flag | Environment Variable | Default | Description

| `--help`, `-h`
|
|
| show help

| `--version`, `-v`
|
|
| print the version
|===

== Advanced Options

|===
| Flag | Environment Variable | Default | Description

| `--agent-token-file` value
| `K3S_AGENT_TOKEN_FILE`
|
| File containing the agent-token

| `--token-file` value
| `K3S_TOKEN_FILE`
|
| File containing the token

| `--service-node-port-range` value
|
| "30000-32767"
| Port range to reserve for services with NodePort visibility

| `--service-pipe-file` value
|
|
| Path to write service port proxy commands to

| `--etcd-servers` value
|
|
| Comma-separated list of etcd servers

| `--etcd-cafile` value
|
|
| SSL Certificate Authority file used to secure etcd communication

| `--etcd-certfile` value
|
|
| SSL certification file used to secure etcd communication

| `--etcd-keyfile` value
|
|
| SSL key file used to secure etcd communication

| `--default-local-storage-path` value
|
| `/var/lib/rancher/k3s/storage`
| Default local storage path for local provisioner storage class

| `--system-default-registry` value
|
|
| Private registry to be used for all system images

| `--service-cidr` value
| `K3S_SERVICE_CIDR`
| "10.43.0.0/16"
| Network CIDR to use for services IPs

| `--cluster-cidr` value
| `K3S_CLUSTER_CIDR`
| "10.42.0.0/16"
| Network CIDR to use for pod IPs

| `--cluster-dns` value
| `K3S_CLUSTER_DNS`
| "10.43.0.10"
| IPv4 Cluster IP for coredns service. Should be in your service-cidr range

| `--cluster-domain` value
| `K3S_CLUSTER_DOMAIN`
| "cluster.local"
| Cluster Domain

| `--flannel-backend` value
| `K3S_FLANNEL_BACKEND`
| "vxlan"
| One of 'none', 'vxlan', 'host-gw', 'wireguard-native'

| `--flannel-ipv6-masq`
|
| false
| Enable IPv6 masquerade for flannel

| `--flannel-external-ip`
|
| false
| Use external IP for flannel

| `--disable` value
|
|
| Do not deploy packaged components and delete any deployed components (valid items: coredns, servicelb, traefik, local-storage, metrics-server)

| `--disable-scheduler`
|
| false
| Disable Kubernetes default scheduler

| `--disable-cloud-controller`
|
| false
| Disable k3s default cloud controller manager

| `--disable-network-policy`
|
| false
| Disable k3s default network policy controller

| `--disable-helm-controller`
|
| false
| Disable Helm controller

| `--embedded-registry`
|
| false
| Enable embedded distributed container registry; requires use of embedded etcd

| `--supervisor-metrics`
|
| false
| Expose supervisor metrics to client interface
|===

== K3s Server CLI Help

If you run `k3s server --help`, you'll see a list of all available options:

[,bash]
----
NAME:
   k3s server - Run management server

USAGE:
   k3s server [OPTIONS]

OPTIONS:
   --config FILE, -c FILE                     (config) Load configuration from FILE
   --debug                                    (logging) Turn on debug logs [$K3S_DEBUG]
   -v value                                   (logging) Number for the log level verbosity (default: 0)
   --vmodule value                            (logging) Comma-separated list of pattern=N settings for file-filtered logging
   --log value, -l value                      (logging) Log to file
   --alsologtostderr                          (logging) Log to standard error as well as file (if set)
   --bind-address value                       (listener) k3s bind address (default: 0.0.0.0)
   --https-listen-port value                  (listener) HTTPS listen port (default: 6443)
   --advertise-address value                  (listener) IPv4/IPv6 address that apiserver uses to advertise to members of the cluster
   --advertise-port value                     (listener) Port that apiserver uses to advertise to members of the cluster (default: 0)
   --tls-san value                            (listener) Add additional hostname or IP as a Subject Alternative Name in the TLS cert
   --tls-san-security                         (listener) Protect the server TLS cert by refusing to add Subject Alternative Names not associated with the kubernetes cluster or the machine itself (default: true)
   --data-dir value, -d value                 (data) Folder to hold state (default: "/var/lib/rancher/k3s") [$K3S_DATA_DIR]
   --disable-agent                            (experimental) Do not run a local agent and register a node
   --cluster-cidr value                       (networking) Network CIDR to use for pod IPs (default: "10.42.0.0/16")
   --service-cidr value                       (networking) Network CIDR to use for services IPs (default: "10.43.0.0/16")
   --service-node-port-range value            (networking) Port range to reserve for services with NodePort visibility (default: "30000-32767")
   --cluster-dns value                        (networking) IPv4 Cluster IP for coredns service. Should be in your service-cidr range (default: 10.43.0.10)
   --cluster-domain value                     (networking) Cluster Domain (default: "cluster.local")
   --flannel-backend value                    (networking) Backend ('none', 'vxlan', 'host-gw', 'wireguard-native') (default: "vxlan")
   --flannel-ipv6-masq                        (networking) Enable IPv6 masquerade for flannel
   --flannel-external-ip                      (networking) Use node external IP addresses for Flannel traffic
   --egress-selector-mode value               (networking) One of 'agent', 'cluster', 'pod', 'disabled' (default: "agent")
   --servicelb-namespace value                (networking) Namespace of the servicelb pods (default: "kube-system")
   --write-kubeconfig value, -o value         (client) Write kubeconfig that can be used to connect to the cluster to this path [$K3S_KUBECONFIG_OUTPUT]
   --write-kubeconfig-mode value              (client) Write kubeconfig with this mode [$K3S_KUBECONFIG_MODE]
   --helm-job-image value                     (helm) Default image to use for helm jobs
   --token value, -t value                    (cluster) Shared secret used to join a server or agent to a cluster [$K3S_TOKEN]
   --token-file value                         (cluster) File containing the token [$K3S_TOKEN_FILE]
   --agent-token value                        (cluster) Shared secret used to join agents to the cluster, but not servers [$K3S_AGENT_TOKEN]
   --agent-token-file value                   (cluster) File containing the agent-token [$K3S_AGENT_TOKEN_FILE]
   --server value, -s value                   (cluster) Server to connect to, used to join a cluster [$K3S_URL]
   --cluster-init                             (cluster) Initialize a new cluster using embedded etcd
   --cluster-reset                            (cluster) Forget all peers and become a single-member cluster
   --cluster-reset-restore-path value         (cluster) Path to snapshot file to be restored
   --kube-apiserver-arg value                 (flags) Customized flag for kube-apiserver process
   --etcd-arg value                           (flags) Customized flag for etcd process
   --kube-controller-manager-arg value        (flags) Customized flag for kube-controller-manager process
   --kube-scheduler-arg value                 (flags) Customized flag for kube-scheduler process
   --kube-cloud-controller-manager-arg value  (flags) Customized flag for kube-cloud-controller-manager process
   --datastore-endpoint value                 (db) Specify etcd, NATS, MySQL, Postgres, or SQLite (default) data source name [$K3S_DATASTORE_ENDPOINT]
   --datastore-cafile value                   (db) TLS Certificate Authority file used to secure datastore backend communication [$K3S_DATASTORE_CAFILE]
   --datastore-certfile value                 (db) TLS certification file used to secure datastore backend communication [$K3S_DATASTORE_CERTFILE]
   --datastore-keyfile value                  (db) TLS key file used to secure datastore backend communication [$K3S_DATASTORE_KEYFILE]
   --etcd-expose-metrics                      (db) Expose etcd metrics to client interface. (default: false)
   --etcd-disable-snapshots                   (db) Disable automatic etcd snapshots
   --etcd-snapshot-name value                 (db) Set the base name of etcd snapshots (default: etcd-snapshot-<unix-timestamp>) (default: "etcd-snapshot")
   --etcd-snapshot-schedule-cron value        (db) Snapshot interval time in cron spec. eg. every 5 hours '0 */5 * * *' (default: "0 */12 * * *")
   --etcd-snapshot-retention value            (db) Number of local snapshots to retain on each server node (default: 5)
   --etcd-snapshot-dir value                  (db) Directory to save db snapshots. (default: ${data-dir}/db/snapshots)
   --etcd-snapshot-compress                   (db) Compress etcd snapshot
   --etcd-s3                                  (db) Enable backup to S3
   --etcd-s3-endpoint value                   (db) S3 endpoint url (default: "s3.amazonaws.com")
   --etcd-s3-endpoint-ca value                (db) S3 custom CA cert to connect to S3 endpoint
   --etcd-s3-skip-ssl-verify                  (db) Disables S3 SSL certificate validation
   --etcd-s3-access-key value                 (db) S3 access key [$AWS_ACCESS_KEY_ID]
   --etcd-s3-secret-key value                 (db) S3 secret key [$AWS_SECRET_ACCESS_KEY]
   --etcd-s3-bucket value                     (db) S3 bucket name
   --etcd-s3-region value                     (db) S3 region / bucket location (optional) (default: "us-east-1")
   --etcd-s3-folder value                     (db) S3 folder
   --etcd-s3-proxy value                      (db) Proxy server to use when connecting to S3, overriding any proxy-releated environment variables
   --etcd-s3-config-secret value              (db) Name of secret in the kube-system namespace used to configure S3, if etcd-s3 is enabled and no other etcd-s3 options are set
   --etcd-s3-insecure                         (db) Disables S3 over HTTPS
   --etcd-s3-timeout value                    (db) S3 timeout (default: 5m0s)
   --default-local-storage-path value         (storage) Default local storage path for local provisioner storage class
   --system-default-registry value            (system) Private registry to be used for all system images [$K3S_SYSTEM_DEFAULT_REGISTRY]
   --system-default-registry-secret value     (system) Name of secret in the kube-system namespace used to provide registry credentials, if private registry is enabled and no cloud credential provider is used
   --vpn-auth value                           (vpn) (experimental) Credentials for VPN provider. It must include the tearkey, but also optional other credentials depending on the VPN provider
   --vpn-auth-file value                      (vpn) (experimental) File containing credentials for VPN provider
   --disable value                            (components) Do not deploy packaged components and delete any deployed components (valid items: coredns, servicelb, traefik, local-storage, metrics-server)
   --disable-scheduler                        (components) Disable Kubernetes default scheduler
   --disable-cloud-controller                 (components) Disable k3s default cloud controller manager
   --disable-network-policy                   (components) Disable k3s default network policy controller
   --disable-helm-controller                  (components) Disable Helm controller
   --embedded-registry                        (components) Enable embedded distributed container registry; requires use of embedded etcd
   --supervisor-metrics                       (components) Expose supervisor metrics to client interface
   --node-name value                          (agent/node) Node name [$K3S_NODE_NAME]
   --with-node-id                             (agent/node) Append id to node name
   --node-label value                         (agent/node) Registering and starting kubelet with set of labels
   --node-taint value                         (agent/node) Registering kubelet with set of taints
   --image-credential-provider-config-map value (agent/node) The name of the ConfigMap in kube-system namespace that contains the credential provider config
   --docker                                   (agent/runtime) (deprecated) Use cri-dockerd instead of containerd
   --container-runtime-endpoint value         (agent/runtime) Disable embedded containerd and use the given CRL socket
   --container-runtime-endpoint-mode value    (agent/runtime) Determines how containerd endpoint is initialized, valid modes: system, bundled, remote (default: "bundled")
   --pause-image value                        (agent/runtime) Customized pause image for containerd or docker sandbox (default: "rancher/mirrored-pause:3.6")
   --private-registry value                   (agent/runtime) User provided registry configuration file (default: "/etc/rancher/k3s/registries.yaml")
   --node-ip value, -i value                  (agent/networking) IPv4/IPv6 addresses to advertise for node
   --node-external-ip value                   (agent/networking) IPv4/IPv6 external addresses to advertise for node
   --resolv-conf value                        (agent/networking) Kubelet resolv.conf file [$K3S_RESOLV_CONF]
   --flannel-iface value                      (agent/networking) Override default flannel interface
   --flannel-conf value                       (agent/networking) Override default flannel config file
   --flannel-cni-conf value                   (agent/networking) Override default flannel cni config file
   --kubelet-arg value                        (agent/flags) Customized flag for kubelet process
   --kube-proxy-arg value                     (agent/flags) Customized flag for kube-proxy process
   --protect-kernel-defaults                  (agent/node) Kernel tuning behavior. If set, error if kernel tunables are different than kubelet defaults.
   --secrets-encryption                       (security) Enable secret encryption at rest
   --secrets-encryption-config-file value     (security) Custom secret encryption configuration file
   --enable-pprof                             (experimental) Enable pprof endpoint on supervisor and apiserver port
   --rootless                                 (experimental) Run rootless
   --prefer-bundled-bin                       (experimental) Prefer bundled userspace binaries over host binaries
   --selinux                                  (agent/node) Enable SELinux in containerd [$K3S_SELINUX]
   --lb-server-port value                     (agent/node) Local port for supervisor client load-balancer. If the supervisor and apiserver are not colocated an additional port 1 less than this port will also be used for the apiserver client load-balancer. (default: 6444) [$K3S_LB_SERVER_PORT]
----
