= Acesso ao Cluster
:page-languages: [en, ja, ko, zh]
:revdate: 2025-09-15
:page-revdate: {revdate}

O arquivo kubeconfig do administrador armazenado em `/etc/rancher/k3s/k3s.yaml` pode ser usado para fornecer acesso ao cluster Kubernetes. Este arquivo concede acesso como o usuário `system:admin` e como o grupo `system:masters`, que são codificados de forma fixa pelo Kubernetes para ter acesso irrestrito a todos os recursos do cluster.

O comando `kubectl` que vem com o K3s está configurado para carregar configurações deste caminho por padrão. Se você instalou ferramentas de linha de comando upstream do Kubernetes, como kubectl ou Helm, você precisa configurá-las com o caminho kubeconfig correto. Isso pode ser feito exportando a variável de ambiente `KUBECONFIG` ou invocando a flag de linha de comando `--kubeconfig`. Consulte os exemplos abaixo para mais detalhes.

* Exporte a variável de ambiente KUBECONFIG:
+
[,bash]
----
export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
kubectl get pods --all-namespaces
helm ls --all-namespaces
----

* Especifique a localização do arquivo kubeconfig no comando:
[,bash]
----
kubectl --kubeconfig /etc/rancher/k3s/k3s.yaml get pods --all-namespaces
helm --kubeconfig /etc/rancher/k3s/k3s.yaml ls --all-namespaces
----

== Acessando o cluster externamente com o kubectl

Copie `/etc/rancher/k3s/k3s.yaml` em sua máquina localizada fora do cluster como `~/.kube/config`. Em seguida, substitua o valor do campo `server` pelo IP ou nome do seu servidor K3s. `kubectl` agora pode gerenciar seu cluster K3s.

[NOTE]
====
O K3s atualiza automaticamente os certificados dentro do kubeconfig do administrador toda vez que inicia. Se você fizer uma cópia deste arquivo, precisará atualizar manualmente essas cópias para garantir que os certificados embutidos não expirem.
====
