= Métriques
:page-languages: [en, ja, ko, zh]
:revdate: 2025-09-16
:page-revdate: {revdate}

K3s fournit des métriques pour surveiller la santé et la performance du cluster.

La plupart des métriques sont fournies par des composants individuels. Consultez la documentation spécifique à chaque composant pour plus d'informations :

* https://coredns.io/plugins/metrics/[métriques de coredns]
* https://etcd.io/docs/v3.5/metrics/[métriques d'etcd]

Des métriques supplémentaires peuvent être fournies par d'autres composants. Consultez la documentation du projet en amont pour tout composant non listé ci-dessus.

== Métriques du superviseur

Lorsque K3s est démarré avec `supervisor-metrics: true`, les métriques sont exposées par le processus K3s et peuvent être accessibles via le point de terminaison `/metrics` sur chaque nœud au port `6443` :

[,sh]
----
kubectl get --server https://NODENAME:6443 --raw /metrics
----

Le processus de superviseur K3s expose les métriques suivantes :

* Métriques de gestion du cluster K3s
* https://github.com/rancher/lasso/blob/main/README.md#lasso-controller[métriques du contrôleur Lasso]
* https://github.com/kubernetes/client-go/blob/master/README.md[métriques du client Kubernetes et de la file d'attente de travail]
* https://kubernetes.io/docs/reference/instrumentation/node-metrics/[Métriques des nœuds Kubernetes]
* https://kubernetes.io/docs/reference/instrumentation/metrics/[Métriques des composants Kubernetes]
* https://pkg.go.dev/runtime/metrics#hdr-Supported_metrics[métriques du composant d'exécution Go]

Si le registre intégré de K3s est activé, le processus de superviseur K3s expose également les métriques suivantes :

* https://spegel.dev/docs/metrics/[métriques de Spegel]
* https://github.com/libp2p/go-libp2p/blob/master/README.md[métriques de libp2p]

K3s exécute tous les composants Kubernetes dans le processus principal de K3s. Puisque Kubernetes utilise un registre de métriques Prometheus unique par processus, les métriques pour tous les composants sont disponibles via tous les points de terminaison de métriques exposés. Si vous scrappez tous les points de terminaison de métriques individuels, vous pourriez constater que vous collectez des métriques en double. Il est seulement nécessaire de scrapper un seul point de terminaison de métriques K3s pour obtenir des métriques pour tous les composants Kubernetes intégrés.

== Métriques de gestion du cluster K3s

=== k3s_certificate_expiration_seconds

Durée de vie restante en secondes du certificat, étiquetée par le sujet du certificat et les usages.

* Type : Gauge
* Libellés : `*subject*`, `*usage*`

=== k3s_loadbalancer_server_connections

Nombre de connexions actuelles au serveur de répartition de charge, étiqueté par le nom du répartiteur de charge et l'adresse du serveur.

* Type : Gauge
* Libellés : `*name*`, `*server*`

=== k3s_loadbalancer_server_health

État de santé actuel des serveurs backend du répartiteur de charge, étiqueté par le nom du répartiteur de charge et l'adresse du serveur.

L'état est un énuméré de 0=INVALID, 1=FAILED, 2=STANDBY, 3=UNCHECKED, 4=RECOVERING, 5=HEALTHY, 6=PREFERRED, 7=ACTIVE.

* Type : Gauge
* Libellés : `*name*`, `*server*`

=== k3s_loadbalancer_dial_duration_seconds

Temps en secondes nécessaire pour établir une connexion à un serveur backend, étiqueté par le nom du répartiteur de charge et le statut de succès/échec.

* Type : Histogramme
* Libellés : `*name*`, `*status*`

=== k3s_etcd_snapshot_save_duration_seconds

Temps total en secondes nécessaire pour compléter le processus d'instantané etcd, étiqueté par le statut de succès/échec.

* Type : Histogramme
* Libellés : `*status*`

=== k3s_etcd_snapshot_save_local_duration_seconds

Temps total en secondes nécessaire pour sauvegarder un fichier d'instantané local, étiqueté par le statut de succès/échec.

* Type : Histogramme
* Libellés : `*status*`

=== k3s_etcd_snapshot_save_s3_duration_seconds

Temps total en secondes nécessaire pour télécharger un fichier d'instantané sur S3, étiqueté par le statut de succès/échec.

* Type : Histogramme
* Libellés : `*status*`

=== k3s_etcd_snapshot_reconcile_duration_seconds

Temps total en secondes nécessaire pour synchroniser la liste des instantanés etcd, étiqueté par le statut de succès/échec.

* Type : Histogramme
* Libellés : `*status*`

=== k3s_etcd_snapshot_reconcile_local_duration_seconds

Temps total en secondes nécessaire pour lister les fichiers d'instantané locaux, étiqueté par le statut de succès/échec.

* Type : Histogramme
* Libellés : `*status*`

=== k3s_etcd_snapshot_reconcile_s3_duration_seconds

Temps total en secondes nécessaire pour lister les fichiers d'instantané S3, étiqueté par le statut de succès/échec.

* Type : Histogramme
* Libellés : `*status*`
