= Métricas
:page-languages: [en, ja, ko, zh]
:revdate: 2025-09-16
:page-revdate: {revdate}

K3s proporciona métricas para monitorizar la salud y el rendimiento del clúster.

La mayoría de las métricas son proporcionadas por componentes individuales. Consulta la siguiente documentación específica de cada componente para más información:

* https://coredns.io/plugins/metrics/[métricas de coredns]
* https://etcd.io/docs/v3.5/metrics/[métricas de etcd]

Métricas adicionales pueden ser proporcionadas por otros componentes. Consulta la documentación del proyecto en sentido ascendente para cualquier componente no listado anteriormente.

== Métricas del Supervisor

Cuando K3s se inicia con `supervisor-metrics: true`, el proceso de K3s expone las métricas, que se pueden acceder mediante el endpoint `/metrics` en cada nodo en el puerto `6443`:

[,sh]
----
kubectl get --server https://NODENAME:6443 --raw /metrics
----

El proceso supervisor de K3s expone las siguientes métricas:

* Métricas de Gestión del Clúster K3s
* https://github.com/rancher/lasso/blob/main/README.md#lasso-controller[métricas del controlador Lasso]
* https://github.com/kubernetes/client-go/blob/master/README.md[métricas del cliente Kubernetes y de la cola de trabajo]
* https://kubernetes.io/docs/reference/instrumentation/node-metrics/[Métricas de nodo de Kubernetes]
* https://kubernetes.io/docs/reference/instrumentation/metrics/[Métricas de componentes de Kubernetes]
* https://pkg.go.dev/runtime/metrics#hdr-Supported_metrics[métricas del tiempo de ejecución de Go]

Si el registro embebido de K3s está habilitado, el proceso supervisor de K3s también expone las siguientes métricas:

* https://spegel.dev/docs/metrics/[métricas de Spegel]
* https://github.com/libp2p/go-libp2p/blob/master/README.md[métricas de libp2p]

K3s ejecuta todos los componentes de Kubernetes en el proceso principal de K3s. Dado que Kubernetes utiliza un único registro de métricas de Prometheus por proceso, las métricas de todos los componentes están disponibles a través de todos los puntos finales de métricas expuestos. Si recoges todos los puntos finales de métricas individuales, puede que encuentres que estás recopilando métricas duplicadas. Solo es necesario recoger un único punto final de métricas de K3s para obtener métricas de todos los componentes de Kubernetes integrados.

== Métricas de Gestión del Clúster K3s

=== k3s_certificate_expiration_seconds

Tiempo de vida restante en segundos del certificado, etiquetado por el sujeto del certificado y los usos.

* Tipo: Medidor
* Etiquetas: `*subject*`, `*usage*`

=== k3s_loadbalancer_server_connections

Conteo de conexiones actuales al servidor del equilibrador de carga, etiquetado por el nombre del equilibrador de carga y la dirección del servidor.

* Tipo: Medidor
* Etiquetas: `*name*`, `*server*`

=== k3s_loadbalancer_server_health

Estado de salud actual de los servidores backend del equilibrador de carga, etiquetado por el nombre del equilibrador de carga y la dirección del servidor.

El estado es un enum de 0=INVÁLIDO, 1=FALLO, 2=EN ESPERA, 3=NO VERIFICADO, 4=RECUPERANDO, 5=SALUDABLE, 6=PREFERIDO, 7=ACTIVO.

* Tipo: Medidor
* Etiquetas: `*name*`, `*server*`

=== k3s_loadbalancer_dial_duration_seconds

Tiempo en segundos tomado para establecer una conexión con un servidor backend, etiquetado por el nombre del equilibrador de carga y el estado de éxito/fallo.

* Tipo: Histograma
* Etiquetas: `*name*`, `*status*`

=== k3s_etcd_snapshot_save_duration_seconds

Tiempo total en segundos tomado para completar el proceso de instantánea de etcd, etiquetado por el estado de éxito/fallo.

* Tipo: Histograma
* Etiquetas: `*status*`

=== k3s_etcd_snapshot_save_local_duration_seconds

Tiempo total en segundos tomado para guardar un archivo de instantánea local, etiquetado por el estado de éxito/fallo.

* Tipo: Histograma
* Etiquetas: `*status*`

=== k3s_etcd_snapshot_save_s3_duration_seconds

Tiempo total en segundos empleado para subir un archivo de instantánea a S3, etiquetado por el estado de éxito/fallo.

* Tipo: Histograma
* Etiquetas: `*status*`

=== k3s_etcd_snapshot_reconcile_duration_seconds

Tiempo total en segundos empleado para sincronizar la lista de instantáneas de etcd, etiquetado por el estado de éxito/fallo.

* Tipo: Histograma
* Etiquetas: `*status*`

=== k3s_etcd_snapshot_reconcile_local_duration_seconds

Tiempo total en segundos empleado para listar archivos de instantáneas locales, etiquetado por el estado de éxito/fallo.

* Tipo: Histograma
* Etiquetas: `*status*`

=== k3s_etcd_snapshot_reconcile_s3_duration_seconds

Tiempo total en segundos empleado para listar archivos de instantáneas de S3, etiquetado por el estado de éxito/fallo.

* Tipo: Histograma
* Etiquetas: `*status*`
