= FAQ
:page-languages: [en, ja, ko, zh]
:revdate: 2024-09-11
:page-revdate: {revdate}

Die FAQ wird regelmäßig aktualisiert und soll die Fragen beantworten, die unsere Benutzer am häufigsten zu K3s stellen.

== Ist K3s ein geeigneter Ersatz für Kubernetes?

K3s ist eine von der CNCF zertifizierte Kubernetes-Distribution und kann alles tun, was von einem standardmäßigen Kubernetes-Cluster verlangt wird. Es ist lediglich eine leichtere Version. Siehe die xref:introduction.adoc[Hauptseite] der Dokumentation für weitere Details.

== Wie kann ich meinen eigenen Ingress anstelle von Traefik verwenden?

Starten Sie einfach den K3s-Server mit `--disable=traefik` und stellen Sie Ihren Ingress bereit.

== Unterstützt K3s Windows?

Zurzeit unterstützt K3s Windows nicht nativ, jedoch sind wir in Zukunft offen für diese Idee.

== Was genau sind Server und Agenten?

Für eine Aufschlüsselung der Komponenten, die einen Server und einen Agenten ausmachen, siehe die xref:architecture.adoc[Architekturseite].

== Wie kann ich K3s aus dem Quellcode erstellen?

Bitte beziehen Sie sich auf die K3s https://github.com/k3s-io/k3s/blob/main/BUILDING.md[BUILDING.md] mit Anweisungen.

== Wo sind die K3s-Protokolle?

Der Standort der K3s-Protokolle variiert je nachdem, wie Sie K3s ausführen und welches Betriebssystem der Knoten hat.

* Wenn es über die Befehlszeile ausgeführt wird, werden die Protokolle an stdout und stderr gesendet.
* Wenn es unter openrc ausgeführt wird, werden die Protokolle unter `/var/log/k3s.log` erstellt.
* Wenn es unter Systemd ausgeführt wird, werden die Protokolle an Journald gesendet und können mit `journalctl -u k3s` angezeigt werden.
* Pod-Protokolle finden Sie unter `/var/log/pods`.
* Die Containerd-Protokolle finden Sie unter `/var/lib/rancher/k3s/agent/containerd/containerd.log`.

Sie können detailliertere Protokolle generieren, indem Sie das `--debug` Flag beim Starten von K3s (oder `debug: true` in der Konfigurationsdatei) verwenden.

Kubernetes verwendet ein Protokollierungsframework, das als `klog` bekannt ist und eine einzige Protokollkonfiguration für alle Komponenten innerhalb eines Prozesses nutzt.
Da K3s alle Kubernetes-Komponenten innerhalb eines einzigen Prozesses ausführt, ist es nicht möglich, unterschiedliche Protokollebenen oder Ziele für einzelne Kubernetes-Komponenten zu konfigurieren.
Die Verwendung der `-v=<level>` oder `--vmodule=<module>=<level>` Komponentenargumente wird wahrscheinlich nicht den gewünschten Effekt haben.

Siehe xref:advanced.adoc#_additional_logging_sources[Zusätzliche Protokollierungsquellen] für noch mehr Protokolloptionen.

== Kann ich K3s in Docker ausführen?

Ja, es gibt mehrere Möglichkeiten, K3s in Docker auszuführen. Siehe xref:advanced.adoc#_running_k3s_in_docker[Erweiterte Optionen] für weitere Details.

== Was ist der Unterschied zwischen K3s Server- und Agent-Token?

Für weitere Informationen zur Verwaltung von K3s-Join-Token siehe die xref:cli/token.adoc[`k3s token` Dokumentation des Befehls].

== Wie kompatibel sind verschiedene Versionen von K3s?

Im Allgemeinen gilt die https://kubernetes.io/docs/setup/release/version-skew-policy/[Richtlinie zur Versionsabweichung von Kubernetes].

Kurz gesagt, Server können neuer sein als Agenten, aber Agenten dürfen nicht neuer sein als Server.

== Ich habe ein Problem, wo kann ich Hilfe bekommen?

Wenn Sie ein Problem mit der Bereitstellung von K3s haben, sollten Sie:

. Überprüfen Sie die Seite xref:known-issues.adoc[Bekannte Probleme].
. Überprüfen Sie, ob Sie alle xref:installation/requirements.adoc#_operating_systems[zusätzlichen Betriebssystemvorbereitungen] abgeschlossen haben. Führen Sie `k3s check-config` aus und stellen Sie sicher, dass es erfolgreich verläuft.
. Durchsuchen Sie die K3s https://github.com/k3s-io/k3s/issues[Probleme] und https://github.com/k3s-io/k3s/discussions[Diskussionen] nach einem, der Ihrem Problem entspricht.
. Treten Sie dem https://slack.rancher.io/[Rancher Slack] K3s-Kanal bei, um Hilfe zu erhalten.
. Reichen Sie ein https://github.com/k3s-io/k3s/issues/new/choose[Neues Problem] auf dem K3s Github ein, in dem Sie Ihr Setup und das Problem, das Sie erleben, beschreiben.
