= Kurzanleitung
:page-languages: [en, ja, ko, zh]
:revdate: 2026-03-03
:page-revdate: {revdate}

Dieses Handbuch hilft Ihnen, schnell einen Cluster mit den Standardoptionen zu starten. Stellen Sie sicher, dass Ihre Knoten die xref:installation/requirements.adoc[Anforderungen] erfüllen, bevor Sie fortfahren.

* Konsultieren Sie die xref:installation/installation.adoc[Installationsseite] für detailliertere Informationen zur Installation und Konfiguration von K3s.
* Für Informationen darüber, wie die K3s-Komponenten zusammenarbeiten, siehe die xref:architecture.adoc[Architekturseite].
* Wenn Sie neu bei Kubernetes sind, haben die https://kubernetes.io/docs/tutorials/kubernetes-basics/[offiziellen Kubernetes-Dokumente] großartige Tutorials, die die Grundlagen abdecken, mit denen alle Clusteradministratoren vertraut sein sollten.

[IMPORTANT]
====
Sie können jede K3s Prime-Version verwenden, die auf der Prime Artifacts-URL für die in diesen Schritten genannten Assets aufgeführt ist. Um mehr über die Prime Artifacts URL zu erfahren, siehe unsere https://scc.suse.com/rancher-docs/rancherprime/latest/en/reference-guide.html#prime-artifacts-url[Prime-exklusive Dokumentation]. Eine Authentifizierung ist erforderlich. Verwenden Sie Ihre https://scc.suse.com/home[SUSE Customer Center (SCC)] Anmeldeinformationen, um sich anzumelden.
====


== Installationsskript

{k3s-product-name} bietet ein Installationsskript, das eine bequeme Möglichkeit ist, es als Dienst auf systemd- oder openrc-basierten Systemen zu installieren. Dieses Skript ist verfügbar unter https://get.k3s.io.. Um {k3s-product-name} mit dieser Methode zu installieren, gehen Sie wie folgt vor:

Führen Sie den Installer aus, wobei `INSTALL_K3S_ARTIFACT_URL` die https://scc.suse.com/rancher-docs/rancherprime/latest/en/reference-guide.html#prime-artifacts-url[Prime Artifacts URL] ist und `INSTALL_K3S_CHANNEL` ein Release-Kanal ist, den Sie abonnieren können und der standardmäßig auf `stable` eingestellt ist. In diesem Beispiel gibt Ihnen `INSTALL_K3S_CHANNEL="latest"` die neueste Version von {k3s-product-name}.

[,bash]
----
curl -sfL https://get.k3s.io | INSTALL_K3S_ARTIFACT_URL=<PRIME-ARTIFACTS-URL>/k3s INSTALL_K3S_CHANNEL="latest" sh -
----
Wenn Sie eine Version angeben möchten, setzen Sie die `INSTALL_RKE2_VERSION` Umgebungsvariable:

[,bash]
----
curl -sfL https://get.k3s.io/ | sudo INSTALL_K3S_ARTIFACT_URL=<PRIME-ARTIFACTS-URL>/k3s INSTALL_K3S_VERSION="<VERSION>" sh -
----

Nach der Ausführung dieser Installation:

* Der K3s-Dienst wird so konfiguriert, dass er nach Neustarts der Knoten oder wenn der Prozess abstürzt oder beendet wird, automatisch neu gestartet wird.
* Zusätzliche Dienstprogramme werden installiert, einschließlich `kubectl`, `crictl`, `ctr`, `k3s-killall.sh` und `k3s-uninstall.sh`
* Eine https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/[kubeconfig-Datei] wird in `/etc/rancher/k3s/k3s.yaml` geschrieben, und das von {k3s-product-name} installierte kubectl wird sie automatisch verwenden.

Eine Einzelknoten-Serverinstallation ist ein voll funktionsfähiger Kubernetes-Cluster, einschließlich aller Datenspeicher-, Steuerungsebene-, Kubelet- und Container-Laufzeitkomponenten, die erforderlich sind, um Arbeitslast-Pods zu hosten. Es ist nicht notwendig, zusätzliche Server- oder Agenten-Knoten hinzuzufügen, aber Sie möchten dies möglicherweise tun, um zusätzliche Kapazität oder Redundanz zu Ihrem Cluster hinzuzufügen.

Um zusätzliche Agentenknoten zu installieren und sie dem Cluster hinzuzufügen, führen Sie das Installationsskript mit den Umgebungsvariablen `K3S_URL` und `K3S_TOKEN` aus. Hier ist ein Beispiel, das zeigt, wie man einen Agenten hinzufügt:

[,bash]
----
curl -sfL https://get.k3s.io | INSTALL_K3S_ARTIFACT_URL=<PRIME-ARTIFACTS-URL>/k3s K3S_URL=https://myserver:6443 K3S_TOKEN=mynodetoken sh -
----

Die Einstellung des `K3S_URL` Parameters bewirkt, dass der Installer K3s als Agent konfiguriert, anstatt als Server. Der K3s-Agent wird sich beim K3s-Server registrieren, der an der angegebenen URL lauscht. Der Wert, der für `K3S_TOKEN` verwendet werden soll, wird bei `/var/lib/rancher/k3s/server/node-token` auf Ihrem Serverknoten gespeichert.

[NOTE]
====
Jede Maschine muss einen eindeutigen Hostnamen haben. Wenn Ihre Maschinen keine eindeutigen Hostnamen haben, übergeben Sie die Umgebungsvariable `K3S_NODE_NAME` und geben Sie einen Wert mit einem gültigen und eindeutigen Hostnamen für jeden Knoten an.
====


Wenn Sie an weiteren Serverknoten interessiert sind, sehen Sie sich die Seiten xref:datastore/ha-embedded.adoc[Hohe Verfügbarkeit Embedded etcd] und xref:datastore/ha.adoc[Hohe Verfügbarkeit External DB] für weitere Informationen an.
