= Manuelle Upgrades
:page-languages: [en, ja, ko, zh]
:revdate: 2025-12-30
:page-revdate: {revdate}

Sie können K3s entweder mit dem Installationsskript oder durch manuelle Installation der gewünschten Version upgraden.

[NOTE]
====
Beim Upgrade sollten Sie zuerst die Serverknoten einzeln upgraden, gefolgt von den Agentenknoten.
====

[#_release_channels]
== Release-Kanäle

Upgrades, die über das Installationsskript oder mit unserer xref:upgrades/automated.adoc[automatisierten Upgrades]-Funktion durchgeführt werden, können an verschiedene Release-Kanäle gebunden sein. Die folgenden Kanäle sind verfügbar:

|===
| Channel | Beschreibung

| stabil
| (Standard) Stabil wird für Produktionsumgebungen empfohlen. Diese Releases haben eine Phase der Community-Tests durchlaufen.

| neueste
| Neueste zeigt immer auf die höchste nicht-Vorabversion verfügbare Version, bestimmt durch die semver-Reihenfolgeregeln. Diese Releases haben noch keine Phase der Community-Tests durchlaufen.

| v1.33 (Beispiel)
| Es gibt einen Release-Kanal, der an jede Kubernetes-Nebenversion gebunden ist, einschließlich Versionen, die das Ende ihrer Lebensdauer erreicht haben. Diese Kanäle wählen die neueste verfügbare Version für diese Nebenversion aus, nicht unbedingt eine stabile Version.
|===

Für eine umfassende und aktuelle Liste der Kanäle können Sie die https://update.k3s.io/v1-release/channels[k3s-Kanal-Service-API] besuchen. Für weitere technische Details, wie Kanäle funktionieren, siehe das https://github.com/rancher/channelserver[Channelserver-Projekt].

[TIP]
====
Beim Versuch, auf eine neue Version von K3s zu upgraden, gilt die https://kubernetes.io/docs/setup/release/version-skew-policy/[Kubernetes-Version-Skew-Richtlinie]. Stellen Sie sicher, dass Ihr Plan beim Upgrade keine Zwischenversionen überspringt. Der System-Upgrade-Controller selbst schützt nicht vor nicht unterstützten Änderungen an der Kubernetes-Version.
====


== K3s mit dem Installationsskript upgraden

Um K3s von einer älteren Version zu upgraden, können Sie das Installationsskript erneut ausführen und dabei die gleichen Konfigurationsoptionen verwenden, die Sie ursprünglich beim Ausführen des Installationsskripts verwendet haben.

[IMPORTANT]
.Hinweis
====
Die `INSTALL_K3S_EXEC` Variable, `K3S_` Variablen und die nachfolgenden Shell-Argumente werden alle vom Installationsskript verwendet, um die systemd-Unit und die Umgebungsdatei zu generieren.
Wenn Sie bei der ursprünglichen Ausführung des Installationsskripts eine Konfiguration festgelegt haben, diese jedoch nicht erneut festlegen, wenn Sie das Installationsskript erneut ausführen, gehen die ursprünglichen Werte verloren.

Der Inhalt der xref:installation/configuration.adoc#_configuration_file[Konfigurationsdatei] wird nicht vom Installationsskript verwaltet.
Wenn Sie möchten, dass Ihre Konfiguration unabhängig vom Installationsskript ist, sollten Sie eine Konfigurationsdatei verwenden, anstatt Umgebungsvariablen oder Argumente an das Installationsskript zu übergeben.
====


Das Ausführen des Installationsskripts führt Folgendes aus:

. Die neue k3s-Binärdatei herunterladen
. Die systemd-Unit oder das openrc-init-Skript aktualisieren, um die an das Installationsskript übergebenen Argumente widerzuspiegeln
. Den k3s-Dienst neu starten

[NOTE]
====
Container für Pods laufen weiter, auch wenn K3s beendet wird. Das Installationsskript entleert oder sperrt den Knoten nicht, bevor K3s neu gestartet wird. Wenn Ihre Arbeitslast empfindlich auf kurze Ausfälle des API-Servers reagiert, sollten Sie den Knoten manuell https://kubernetes.io/docs/reference/kubectl/generated/kubectl_drain/[entleeren und sperren] mit `kubectl`, bevor Sie das Installationsskript erneut ausführen, um K3s zu upgraden oder die Konfiguration zu ändern, und ihn danach wieder entsperren.
====

Zum Beispiel, um auf die aktuelle stabile Version zu upgraden:

[,sh]
----
curl -sfL https://get.k3s.io | INSTALL_K3S_ARTIFACT_URL=<PRIME-ARTIFACTS-URL>/k3s <EXISTING_K3S_ENV> sh -s - <EXISTING_K3S_ARGS>
----

Wenn Sie auf eine neuere Version in einem bestimmten Kanal (wie latest) upgraden möchten, können Sie den Kanal angeben:

[,sh]
----
curl -sfL https://get.k3s.io | INSTALL_K3S_ARTIFACT_URL=<PRIME-ARTIFACTS-URL>/k3s INSTALL_K3S_CHANNEL=latest <EXISTING_K3S_ENV> sh -s - <EXISTING_K3S_ARGS>
----

Wenn Sie auf eine bestimmte Version upgraden möchten, können Sie den folgenden Befehl ausführen:

[,sh]
----
curl -sfL https://get.k3s.io | INSTALL_K3S_ARTIFACT_URL=<PRIME-ARTIFACTS-URL>/k3s INSTALL_K3S_VERSION=vX.Y.Z+k3s1 <EXISTING_K3S_ENV> sh -s - <EXISTING_K3S_ARGS>
----

[TIP]
====
Wenn Sie die neue Version von k3s herunterladen, aber nicht starten möchten, können Sie die `INSTALL_K3S_SKIP_START=true` Umgebungsvariable verwenden.
====


== K3s mit der Binärdatei upgraden

Um K3s manuell zu upgraden, können Sie die gewünschte Version der K3s-Binärdatei herunterladen und die vorhandene Binärdatei durch die neue ersetzen.

. Laden Sie die gewünschte Version der K3s-Binärdatei von https://github.com/k3s-io/k3s/releases[releases] herunter.
. Kopieren Sie die heruntergeladene Binärdatei nach `/usr/local/bin/k3s` (oder an Ihren gewünschten Speicherort).
. Starten Sie den k3s- oder k3s-agent-Dienst neu oder starten Sie den k3s-Prozess neu.

[NOTE]
====
Container für Pods laufen weiter, auch wenn K3s beendet wird. Es ist im Allgemeinen sicher, K3s neu zu starten, ohne Pods zu entleeren und den Knoten zu sperren. Wenn Ihre Arbeitslast empfindlich auf kurze Ausfälle des API-Servers reagiert, sollten Sie den Knoten manuell https://kubernetes.io/docs/reference/kubectl/generated/kubectl_drain/[entleeren und sperren] mit `kubectl`, bevor Sie K3s neu starten, und ihn danach wieder entsperren.
====
