= Rollback von K3s
:page-languages: [en, ja, ko, zh]
:revdate: 2026-03-03
:page-revdate: {revdate}

Sie können nach einem Upgrade einen Rollback der K3s Kubernetes-Version durchführen, indem Sie eine Kombination aus einem K3s-Binär-Downgrade und der Wiederherstellung des Datenspeichers anwenden. Rollback kann auf Clustern aller Art durchgeführt werden, einschließlich eines einzelnen SQLite-Knotens, eines externen Datenspeichers oder eines eingebetteten etcd. Beim Rollback auf eine frühere Kubernetes-Nebenversion müssen Sie einen Datenspeicher-Snapshot besitzen, der auf der gewünschten Kubernetes-Nebenversion aufgenommen wurde.

[WARNING]
====
Wenn Sie die Datenbank nicht wiederherstellen können, ist ein Rollback auf eine frühere Nebenversion nicht möglich.
====

== Wichtige Überlegungen

* *Sicherungen:* Stellen Sie vor dem Upgrade sicher, dass Sie einen gültigen Datenbank- oder etcd-Snapshot von Ihrem Cluster haben, das die ältere Version von K3s ausführt. Ohne eine Sicherung ist ein Rollback unmöglich.
* *Potentieller Datenverlust:* Das `k3s-killall.sh` Skript beendet K3s-Prozesse gewaltsam und kann zu Datenverlust führen, wenn Anwendungen nicht ordnungsgemäß heruntergefahren werden.
* *Versionsspezifika:* Überprüfen Sie immer die K3s- und Komponenten-Versionen vor und nach dem Rollback.

== Rollback eines K3s-Clusters

[tabs]
======

SQLite::
+
--
Um einen Rollback eines K3s-Clusters mit einer SQLite-Datenbank durchzuführen, ersetzen Sie die `.db` Datei durch die Kopie der `.db` Datei, die Sie bei der Sicherung Ihrer Datenbank erstellt haben.
--

Eingebettetes etcd::
+
--
Um einen Rollback eines K3s-Clusters mit einem eingebetteten etcd durchzuführen, befolgen Sie diese Schritte: 

. Wenn der Cluster läuft und die Kubernetes-API verfügbar ist, stoppen Sie die Arbeitslasten ordnungsgemäß, indem Sie alle Knoten entleeren: 
+
[,bash]
----
kubectl drain --ignore-daemonsets --delete-emptydir-data <NODE-ONE-NAME> <NODE-TWO-NAME> <NODE-THREE-NAME> ...
----

. Beenden Sie den K3s-Dienst und alle laufenden Pod-Prozesse auf jedem Knoten:
+
[,bash]
----
k3s-killall.sh
----

. Führen Sie auf jedem Knoten einen Rollback der K3s-Binärdatei auf die vorherige Version durch, aber *starten Sie K3s nicht*.

* Cluster mit Internetzugang:

** Serverknoten: 
+
[,bash]
----
curl -sfL https://get.k3s.io | INSTALL_K3S_ARTIFACT_URL=<PRIME-ARTIFACTS-URL>/k3s INSTALL_K3S_VERSION=vX.Y.Zk3s1 INSTALL_K3S_EXEC="server" INSTALL_K3S_SKIP_START="true" sh -
----

** Agentenknoten:
+
[,bash]
----
curl -sfL https://get.k3s.io | INSTALL_K3S_ARTIFACT_URL=<PRIME-ARTIFACTS-URL>/k3s INSTALL_K3S_VERSION=vX.Y.Zk3s1 INSTALL_K3S_EXEC="agent" INSTALL_K3S_SKIP_START="true" sh -
----

* Air-gapped Cluster:

** Laden Sie die Artefakte herunter und führen Sie das xref:installation/airgap.adoc#_install_k3s[Installationsskript] lokal aus. Fügen Sie die Umgebungsvariable `INSTALL_K3S_SKIP_START="true"` hinzu, wenn Sie das Installationsskript ausführen, um zu verhindern, dass K3s gestartet wird.

. Initiieren Sie die Cluster-Wiederherstellung auf dem ersten Serverknoten oder dem Knoten ohne einen `server:` Eintrag in seiner xref:installation/configuration.adoc[K3s-Konfigurationsdatei]. Siehe die xref:cli/etcd-snapshot.adoc#_snapshot_restore_steps[Schritte zur Snapshot-Wiederherstellung] für weitere Informationen: 
+
[,bash]
----
k3s server --cluster-reset --cluster-reset-restore-path=<PATH-TO-SNAPSHOT>
----
+
[WARNING]
====
Dies überschreibt alle Daten im etcd-Datenspeicher. Überprüfen Sie die Integrität des Snapshots, bevor Sie ihn wiederherstellen. Seien Sie sich bewusst, dass große Snapshots lange dauern können, um wiederhergestellt zu werden.
====

. Starten Sie den K3s-Dienst auf dem ersten Serverknoten: 
+
[,bash]
----
systemctl start k3s
----
 
. Entfernen Sie auf den anderen Serverknoten das K3s-Datenbankverzeichnis:
+
[,bash]
----
rm -rf /var/lib/rancher/k3s/server/db
----
 
. Starten Sie den K3s-Dienst auf den anderen Serverknoten: 
+
[,bash]
----
systemctl start k3s
----

. Starten Sie den K3s-Dienst auf allen Agentenknoten:
+
[,bash]
----
systemctl start k3s
----

. Überprüfen Sie den Status des K3s-Dienstes mit `systemctl status k3s`. 
--

Externe Datenbank:: 
+
--
Um einen Rollback eines K3s-Clusters bei Verwendung einer externen Datenbank (z. B. PostgreSQL, MySQL) durchzuführen, befolgen Sie diese Schritte: 

. Wenn der Cluster läuft und die Kubernetes-API verfügbar ist, stoppen Sie die Arbeitslasten ordnungsgemäß, indem Sie alle Knoten entleeren: 
+
[,bash]
----
kubectl drain --ignore-daemonsets --delete-emptydir-data <NODE-ONE-NAME> <NODE-TWO-NAME> <NODE-THREE-NAME> ...
----
+
[NOTE]
====
Dieser Prozess kann laufende Anwendungen stören.
====

. Beenden Sie den K3s-Dienst und alle laufenden Pod-Prozesse auf jedem Knoten:
+
[,bash]
----
k3s-killall.sh
----

. Stellen Sie einen Datenbank-Snapshot wieder her, der vor dem Upgrade von K3s erstellt wurde, und überprüfen Sie die Integrität der Datenbank. Wenn Sie beispielsweise PostgreSQL verwenden, führen Sie den folgenden Befehl aus:
+
[,bash]
----
pg_restore -U <DB-USER> -d <DB-NAME> <BACKUP-FILE>
----

. Führen Sie auf jedem Knoten ein Rollback der K3s-Binärdatei auf die vorherige Version durch. 

* Cluster mit Internetzugang:

** Serverknoten:
+
[,bash]
----
curl -sfL https://get.k3s.io | INSTALL_K3S_ARTIFACT_URL=<PRIME-ARTIFACTS-URL>/k3s INSTALL_K3S_VERSION=vX.Y.Zk3s1 INSTALL_K3S_EXEC="server" sh -
----

** Agentenknoten:
+
[,bash]
----
curl -sfL https://get.k3s.io | INSTALL_K3S_ARTIFACT_URL=<PRIME-ARTIFACTS-URL>/k3s INSTALL_K3S_VERSION=vX.Y.Zk3s1 INSTALL_K3S_EXEC="agent" sh -
----

* Air-gapped Cluster:

** Laden Sie die Artefakte herunter und führen Sie das xref:installation/airgap.adoc#_install_k3s[Installationsskript] lokal aus. Überprüfen Sie die K3s-Version nach der Installation mit `k3s --version` und wenden Sie alle benutzerdefinierten Konfigurationen erneut an, die vor dem Upgrade verwendet wurden. 

. Starten Sie den K3s-Dienst auf jedem Knoten:
+
[,bash]
----
systemctl start k3s
----

. Überprüfen Sie den Status des K3s-Dienstes mit `systemctl status k3s`.
--
======

== Überprüfung 

Überprüfen Sie nach dem Rollback Folgendes: 

* K3s-Version: `k3s --version` 
* Gesundheit des Kubernetes-Clusters: `kubectl get nodes` 
* Funktionalität der Anwendung. 
* Überprüfen Sie die K3s-Protokolle auf Fehler.
