= Aufrüstungen
:page-languages: [en, ja, ko, zh]
:revdate: 2024-09-11
:page-revdate: {revdate}

== Upgrade Ihres K3s-Clusters

xref:upgrades/manual.adoc[Manuelle Upgrades] beschreibt mehrere Techniken zur manuellen Durchführung eines Upgrades Ihres Clusters. Es kann auch als Grundlage für das Upgrade über Drittanbieter-Infrastruktur-als-Code-Tools wie https://www.terraform.io/[Terraform] verwendet werden.

xref:upgrades/automated.adoc[Automatisierte Upgrades] beschreibt, wie Kubernetes-native automatisierte Upgrades mit Ranchers https://github.com/rancher/system-upgrade-controller[system-upgrade-controller] durchgeführt werden.

== Versionsspezifische Hinweise

* *Traefik:* Wenn Traefik nicht deaktiviert ist, installieren K3s-Versionen 1.20 und früher Traefik v1, während K3s-Versionen 1.21 und später Traefik v2 installieren, sofern v1 nicht bereits vorhanden ist. Um von dem älteren Traefik v1 auf Traefik v2 zu upgraden, konsultieren Sie bitte die https://doc.traefik.io/traefik/migrate/v1-to-v2/[Traefik-Dokumentation] und verwenden Sie das https://github.com/traefik/traefik-migration-tool[Migrationstool].
* *K3s-Bootstrap-Daten:* Wenn Sie K3s in einer HA-Konfiguration mit einem externen SQL-Datenspeicher verwenden und Ihre Server (Control-Plane)-Knoten nicht mit dem `--token` CLI-Flag gestartet wurden, können Sie keine zusätzlichen K3s-Server zum Cluster hinzufügen, ohne das Token anzugeben. Stellen Sie sicher, dass Sie eine Kopie dieses Tokens aufbewahren, da es beim Wiederherstellen aus einer Sicherung erforderlich ist. Früher hat K3s die Verwendung eines Tokens bei externen SQL-Datenspeichern nicht durchgesetzt.
 ** Die betroffenen Versionen sind <= v1.19.12+k3s1, v1.20.8+k3s1, v1.21.2+k3s1; die gepatchten Versionen sind v1.19.13+k3s1, v1.20.9+k3s1, v1.21.3+k3s1.
 ** Sie können den Tokenwert von jedem Server, der bereits dem Cluster beigetreten ist, wie folgt abrufen:
+
[,bash]
----
cat /var/lib/rancher/k3s/server/token
----
