= k3s secrets-encrypt
:page-languages: [en, ja, ko, zh]
:revdate: 2026-01-05
:page-revdate: {revdate}

K3s admite la habilitación de la encriptación de secretos en reposo. Para más información, consulta xref:security/secrets-encryption.adoc[Encriptación de Secretos].

== Herramienta de Encriptación de Secretos

[IMPORTANT]
.Puerta de Versión
====
Disponible a partir de https://github.com/k3s-io/k3s/releases/tag/v1.21.8%2Bk3s1[v1.21.8+k3s1]
====


K3s contiene una herramienta CLI `secrets-encrypt`, que permite el control automático sobre lo siguiente:

* Deshabilitar/Habilitar la encriptación de secretos
* Añadir nuevas claves de encriptación
* Rotar y eliminar claves de encriptación
* Reencriptar secretos

[CAUTION]
====
No seguir el procedimiento adecuado para rotar las claves de encriptación puede dejar tu clúster permanentemente dañado. Procede con precaución.
====

[#_encryption_key_rotation]
=== Rotación de Claves de Encriptación

[IMPORTANT]
.Puerta de Versión
====
Disponible a partir de las versiones de septiembre de 2024: v1.30.5+k3s1, v1.31.1+k3s1.
====

[tabs,sync-group-id=se]
======
Servidor Único::
+
--
Para rotar las claves de encriptación de secretos en un clúster de servidor único:

. Inicia el servidor K3s con la bandera `--secrets-encryption`
+
[NOTE]
====
Iniciar K3s sin encriptación y habilitarlo en un momento posterior no está actualmente _soportado_.
====

. Rotar las claves de encriptación de secretos
+
----
k3s secrets-encrypt rotate-keys
----

. Espera a que termine la reencriptación. Observa los registros del servidor, o espera a:
+
[,bash]
----
$ k3s secrets-encrypt status
Encryption Status: Enabled
Current Rotation Stage: reencrypt_finished
----
--

Alta disponibilidad::
+
--
Para rotar las claves de encriptación de secretos en configuraciones de alta disponibilidad:

. Inicia los tres servidores K3s con la bandera `--secrets-encryption`. Por brevedad, los servidores se denominarán S1, S2, S3.
+
[NOTE]
====
Iniciar K3s sin encriptación y habilitarlo en un momento posterior no está actualmente _soportado_.
====

. Rotar las claves de encriptación de secretos en S1
+
[,bash]
----
k3s secrets-encrypt rotate-keys
----

. Espera a que termine la reencriptación. Observa los registros del servidor, o espera a:
+
[,bash]
----
$ k3s secrets-encrypt status
Encryption Status: Enabled
Current Rotation Stage: reencrypt_finished
----
+
[NOTE]
====
K3s reencriptará ~5 secretos por segundo. Los clústeres con un gran número de secretos pueden tardar varios minutos en reencriptarse. Puedes seguir el progreso en los registros del servidor.
====

. Reinicia K3s en S1 con los mismos argumentos. Si ejecutas K3s como un servicio:
+
[,bash]
----
# If using systemd
systemctl restart k3s
# If using openrc
rc-service k3s restart
----

. Una vez que S1 esté en funcionamiento, reinicia K3s en S2 y S3
--
======

=== Rotación de claves de encriptación heredadas

[TIP]
.Nuevo procedimiento
====
Si utilizas versiones de K3s v1.30+, recomendamos usar la xref:#_encryption_key_rotation[Rotación de Claves de Encriptación] en su lugar.
====

[tabs,sync-group-id=se]
======
Servidor Único::
+
--
Para rotar las claves de encriptación de secretos en un clúster de servidor único:

. Inicia el servidor K3s con la bandera `--secrets-encryption`
+
[NOTE]
====
Iniciar K3s sin encriptación y habilitarlo en un momento posterior no está actualmente _soportado_.
====

. Preparación
+
[,bash]
----
k3s secrets-encrypt prepare
----

. Mata y reinicia el servidor K3s con los mismos argumentos. Si ejecutas K3s como un servicio:
+
[,bash]
----
# If using systemd
systemctl restart k3s
# If using openrc
rc-service k3s restart
----

. Rotar
+
[,bash]
----
k3s secrets-encrypt rotate
----

. Mata y reinicia el servidor K3s con los mismos argumentos
. Reencriptar
+
[NOTE]
====
K3s reencriptará ~5 secretos por segundo. +
Los clústeres con un gran número de secretos pueden tardar varios minutos en reencriptarse.
====
+
[,bash]
----
k3s secrets-encrypt reencrypt
----
--

Alta disponibilidad::
+
--
Los pasos son los mismos tanto para las bases de datos embebidas como para los clústeres de bases de datos externas.

Para rotar las claves de encriptación de secretos en configuraciones de alta disponibilidad:

. Inicia los tres servidores K3s con la bandera `--secrets-encryption`. Por brevedad, los servidores se denominarán S1, S2, S3.
+
[NOTE]
====
* Iniciar K3s sin encriptación y habilitarlo en un momento posterior no está actualmente _soportado_.
* Aunque no es obligatorio, se recomienda que elijas un nodo de servidor desde el cual ejecutar los comandos `secrets-encrypt`.
====
. Preparar en S1
+
[,bash]
----
k3s secrets-encrypt prepare
----

. Matar y reiniciar S1 con los mismos argumentos. Si ejecutas K3s como un servicio:
+
[,bash]
----
# If using systemd
systemctl restart k3s
# If using openrc
rc-service k3s restart
----

. Una vez que S1 esté en funcionamiento, matar y reiniciar S2 y S3
. Rotar en S1
+
[,bash]
----
k3s secrets-encrypt rotate
----

. Matar y reiniciar S1 con los mismos argumentos
. Una vez que S1 esté en funcionamiento, matar y reiniciar S2 y S3
. Reencriptar en S1
+
[NOTE]
====
K3s reencriptará ~5 secretos por segundo. +
Los clústeres con un gran número de secretos pueden tardar varios minutos en reencriptarse.
====
+
[,bash]
----
k3s secrets-encrypt reencrypt
----

. Matar y reiniciar S1 con los mismos argumentos
. Una vez que S1 esté en funcionamiento, matar y reiniciar S2 y S3
--
======

=== Desactivar/volver a activar la encriptación de secretos

[tabs,sync-group-id=se]
======
Servidor Único::
+
--
Después de lanzar un servidor con la bandera `--secrets-encryption`, se puede desactivar la encriptación de secretos.

Para desactivar la encriptación de secretos en un clúster de un solo nodo:

. Desactivar
+
[,bash]
----
k3s secrets-encrypt disable
----

. Mata y reinicia el servidor K3s con los mismos argumentos. Si ejecutas K3s como un servicio:
+
[,bash]
----
# If using systemd
systemctl restart k3s
# If using openrc
rc-service k3s restart
----

. Reencriptar con banderas
+
[,bash]
----
k3s secrets-encrypt reencrypt --force --skip
----

Para volver a activar la encriptación de secretos en un clúster de un solo nodo:

. Habilitar
+
[,bash]
----
k3s secrets-encrypt enable
----

. Mata y reinicia el servidor K3s con los mismos argumentos
. Reencriptar con banderas
+
[,bash]
----
k3s secrets-encrypt reencrypt --force --skip
----
--

Alta disponibilidad::
+
--
Después de lanzar un clúster de alta disponibilidad con las banderas `--secrets-encryption`, se puede desactivar la encriptación de secretos.

[NOTE]
====
Aunque no es obligatorio, se recomienda que elijas un nodo de servidor desde el cual ejecutar los comandos `secrets-encrypt`.
====

Por brevedad, los tres servidores utilizados en esta guía se denominarán S1, S2, S3.

Para desactivar la encriptación de secretos en un clúster de alta disponibilidad:

. Desactivar en S1
+
[,bash]
----
k3s secrets-encrypt disable
----

. Matar y reiniciar S1 con los mismos argumentos. Si ejecutas K3s como un servicio:
+
[,bash]
----
# If using systemd
systemctl restart k3s
# If using openrc
rc-service k3s restart
----

. Una vez que S1 esté en funcionamiento, matar y reiniciar S2 y S3
. Reencriptar con banderas en S1
+
[,bash]
----
k3s secrets-encrypt reencrypt --force --skip
----

Para volver a activar la encriptación de secretos en un clúster de alta disponibilidad:

. Habilitar en S1
+
[,bash]
----
k3s secrets-encrypt enable
----

. Matar y reiniciar S1 con los mismos argumentos
. Una vez que S1 esté en funcionamiento, matar y reiniciar S2 y S3
. Reencriptar con banderas en S1
+
[,bash]
----
k3s secrets-encrypt reencrypt --force --skip
----
--
======

=== Estado de encriptación de secretos

La herramienta de encriptación de secretos incluye un comando `status` que muestra información sobre el estado actual de la encriptación de secretos en el nodo.

Un ejemplo del comando en un nodo de un solo servidor:

[,bash]
----
$ k3s secrets-encrypt status
Encryption Status: Enabled
Current Rotation Stage: start
Server Encryption Hashes: All hashes match

Active  Key Type  Name
------  --------  ----
 *      AES-CBC   aescbckey
----

Otro ejemplo en un clúster de alta disponibilidad, después de rotar las claves, pero antes de reiniciar los servidores:

[,bash]
----
$ k3s secrets-encrypt status
Encryption Status: Enabled
Current Rotation Stage: rotate
Server Encryption Hashes: hash does not match between node-1 and node-2

Active  Key Type  Name
------  --------  ----
 *      AES-CBC   aescbckey-2021-12-10T22:54:38Z
        AES-CBC   aescbckey
----

Los detalles de cada sección son los siguientes:

* *Estado de encriptación*: Se muestra si la encriptación de secretos está deshabilitada o habilitada en el nodo
* *Etapa de rotación actual*: Indica la etapa de rotación actual en el nodo. +
Las etapas son: `start`, `prepare`, `rotate`, `reencrypt_request`, `reencrypt_active`, `reencrypt_finished`
* *Hash de encriptación del servidor*: Útil para clústeres HA, esto indica si todos los servidores están en la misma etapa con sus archivos locales. Esto se puede usar para identificar si se requiere un reinicio de los servidores antes de proceder a la siguiente etapa. En el ejemplo de HA anterior, el nodo-1 y el nodo-2 tienen hashes diferentes, lo que indica que actualmente no tienen la misma configuración de encriptación. Reiniciar los servidores sincronizará su configuración.
* *Tabla de claves*: Resume la información sobre las claves de encriptación de secretos encontradas en el nodo.
 ** *Activo*: El "*" indica cuáles, si los hay, de las claves se utilizan actualmente para la encriptación de secretos. Una clave activa es utilizada por Kubernetes para cifrar cualquier nuevo secreto.
 ** *Tipo de clave*: Todas las claves que utilizan esta herramienta son de tipo `AES-CBC`. Consulta más información https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/#providers[aquí.]
 ** *Nombre*: Nombre de la clave de encriptación.
