= バックアップと回復
:page-languages: [en, ja, ko, zh]
:revdate: 2024-09-11
:page-revdate: {revdate}

K3sのバックアップと復元の方法は、使用されるデータストアの種類によって異なります。

[CAUTION]
====
データストア自体のバックアップに加えて、`/var/lib/rancher/k3s/server/token`にあるサーバートークンファイルもバックアップする必要があります。
バックアップから復元する際には、このファイルを復元するか、その値を`--token`オプションに渡す必要があります。
復元時に同じトークン値を使用しない場合、スナップショットは使用できなくなります。トークンはデータストア内の機密データを暗号化するために使用されるためです。
====


== SQLiteを使用したバックアップと復元

SQLiteデータストアをバックアップまたは復元するために特別なコマンドは必要ありません。

* SQLiteデータストアをバックアップするには、`/var/lib/rancher/k3s/server/db/`のコピーを取ります。
* SQLiteデータストアを復元するには、`/var/lib/rancher/k3s/server/db`の内容を復元します（上記で説明したように、トークンも復元してください）。

== 外部データストアを使用したバックアップと復元

外部データストアが使用される場合、バックアップおよび復元操作はK3sの外部で処理されます。データベース管理者は、外部データベースをバックアップするか、スナップショットまたはダンプから復元する必要があります。

データベースが定期的にスナップショットを取得するように設定することをお勧めします。

データベースのスナップショットを取得し、それらからデータベースを復元する方法の詳細については、公式のデータベースドキュメントを参照してください：

* https://dev.mysql.com/doc/refman/8.0/en/replication-snapshot-method.html[公式MySQLドキュメント]
* https://www.postgresql.org/docs/8.3/backup-dump.html[公式PostgreSQLドキュメント]
* https://etcd.io/docs/latest/op-guide/recovery/[公式etcdドキュメント]

== 組み込みetcdデータストアを使用したバックアップと復元

組み込みetcdデータストアのバックアップおよび復元操作に関する情報は、xref:cli/etcd-snapshot.adoc[`k3s etcd-snapshot`コマンドのドキュメント]を参照してください。
