= フラグの廃止
:page-languages: [en, ja, ko, zh]
:revdate: 2024-09-09
:page-revdate: {revdate}

K3sは急速に進化するプロジェクトであり、そのため、フラグや設定オプションを廃止する方法が必要です。このページでは、フラグや設定オプションを廃止する処理について説明します。ユーザーがフラグの削除に驚かないようにするために、このプロセスはhttps://kubernetes.io/docs/reference/using-api/deprecation-policy/[Kubernetes廃止ポリシー]に似ています。

== プロセス

. フラグはいつでも「廃止予定」として宣言できます。
. 「廃止予定」とされたフラグは、すべての現在サポートされているリリースの次のパッチでそのようにラベル付けされなければなりません。さらに、そのフラグは次のマイナーバージョンで廃止されることをユーザーに警告し始めます。
. 次のマイナーバージョンでは、フラグはドキュメントで廃止としてマークされ、コード内では隠しフラグに変換されます。そのフラグは引き続き動作し、ユーザーに警告を発します。
. 次のマイナーバージョンのブランチでは、非推奨のフラグは「非操作的」となり、使用すると致命的なエラーを引き起こします。このエラーは、ユーザーにこのフラグを置き換える新しいフラグや設定を説明しなければなりません。
. 次のマイナーバージョンでは、非操作的なフラグはドキュメントとコードから削除されます。

== 例

処理の例：

* `--foo`はv1.22.14、v1.23.10、v1.24.2に存在します。
* v1.24.2のリリース後、`--foo`を`--new-foo`に置き換えるために廃止することが決定されました。
* v1.22.15、v1.23.11、v1.24.3では、`--foo`は引き続き存在しますが、ユーザーに警告します：
+
----
[Warning] --foo will be deprecated in v1.25.0, use `--new-foo` instead
----
+
`--foo`はv1.22、v1.23、v1.24の期間中、操作可能なフラグとして存在し続けます。

* v1.25.0では、`--foo`はドキュメントで廃止としてマークされ、コード内では隠されます。それは引き続き動作し、ユーザーに`--new-foo`に移行するよう警告します。
* v1.26.0では、`--foo`を使用すると致命的なエラーが発生します。エラーメッセージは次のように表示されます：
+
----
[Fatal] exit 1: --foo is no longer supported, use --new-foo instead
----

* v1.27.0では、`--foo`はすべてのコードと文書から完全に削除されます。
