= Metrics
:page-languages: [en, ja, ko, zh]
:revdate: 2025-09-16
:page-revdate: {revdate}

K3sは、クラスターの健康状態とパフォーマンスを監視するためのメトリクスを提供します。

ほとんどのメトリクスは、個々のコンポーネントによって提供されます。詳細については、以下のコンポーネント固有のドキュメントを参照してください：

* https://coredns.io/plugins/metrics/[corednsメトリクス]
* https://etcd.io/docs/v3.5/metrics/[etcdメトリクス]

追加のメトリクスは、他のコンポーネントによって提供される場合があります。上記にリストされていないコンポーネントについては、アップストリームプロジェクトのドキュメントを参照してください。

== スーパーバイザーメトリクス

K3sが`supervisor-metrics: true`で起動されると、メトリクスはK3sプロセスによって公開され、各ノードのポート`/metrics`で`6443`エンドポイントを介してアクセスできます：

[,sh]
----
kubectl get --server https://NODENAME:6443 --raw /metrics
----

K3sスーパーバイザープロセスは、以下のメトリクスを公開します：

* K3sクラスター管理メトリクス
* https://github.com/rancher/lasso/blob/main/README.md#lasso-controller[Lassoコントローラーメトリクス]
* https://github.com/kubernetes/client-go/blob/master/README.md[Kubernetesクライアントとワークキューのメトリクス]
* https://kubernetes.io/docs/reference/instrumentation/node-metrics/[Kubernetesノードメトリクス]
* https://kubernetes.io/docs/reference/instrumentation/metrics/[Kubernetesコンポーネントメトリクス]
* https://pkg.go.dev/runtime/metrics#hdr-Supported_metrics[Goランタイムメトリクス]

K3sに組み込まれたレジストリが有効になっている場合、K3sスーパーバイザープロセスは以下のメトリクスも公開します：

* https://spegel.dev/docs/metrics/[Spegelメトリクス]
* https://github.com/libp2p/go-libp2p/blob/master/README.md[libp2pメトリクス]

K3sは、主要なK3sプロセス内で全てのKubernetesコンポーネントを実行します。Kubernetesはプロセスごとに単一のPrometheusメトリックレジストリを使用するため、全てのコンポーネントのメトリックは、全ての公開されたメトリックエンドポイントを通じて利用可能です。全ての個別のメトリックエンドポイントをスクレイプすると、重複したメトリックを収集していることに気付くかもしれません。全ての埋め込まれたKubernetesコンポーネントのメトリックを取得するには、単一のK3sメトリックエンドポイントをスクレイプするだけで十分です。

== K3sクラスター管理メトリクス

=== k3s_certificate_expiration_seconds

証明書の残りの有効期限（秒単位）、証明書のサブジェクトと使用法によってラベル付けされています。

* タイプ:ゲージ
* ラベル: `*subject*`, `*usage*`

=== k3s_loadbalancer_server_connections

ロードバランサーサーバーへの現在の接続数、ロードバランサー名とサーバーアドレスによってラベル付けされています。

* タイプ:ゲージ
* ラベル: `*name*`, `*server*`

=== k3s_loadbalancer_server_health

ロードバランサーのバックエンドサーバーの現在の健康状態、ロードバランサー名とサーバーアドレスによってラベル付けされています。

状態は、0=INVALID、1=FAILED、2=STANDBY、3=UNCHECKED、4=RECOVERING、5=HEALTHY、6=PREFERRED、7=ACTIVEの列挙型です。

* タイプ:ゲージ
* ラベル: `*name*`, `*server*`

=== k3s_loadbalancer_dial_duration_seconds

バックエンドサーバーへの接続をダイヤルするのにかかる時間（秒単位）、ロードバランサー名と成功/エラーのステータスによってラベル付けされています。

* タイプ:ヒストグラム
* ラベル: `*name*`, `*status*`

=== k3s_etcd_snapshot_save_duration_seconds

etcdスナップショットプロセスを完了するのにかかる総時間（秒単位）、成功/エラーのステータスによってラベル付けされています。

* タイプ:ヒストグラム
* ラベル: `*status*`

=== k3s_etcd_snapshot_save_local_duration_seconds

ローカルスナップショットファイルを保存するのにかかる総時間（秒単位）、成功/エラーのステータスによってラベル付けされています。

* タイプ:ヒストグラム
* ラベル: `*status*`

=== k3s_etcd_snapshot_save_s3_duration_seconds

スナップショットファイルをS3にアップロードするのにかかる総時間（秒単位）、成功/エラーのステータスによってラベル付けされています。

* タイプ:ヒストグラム
* ラベル: `*status*`

=== k3s_etcd_snapshot_reconcile_duration_seconds

etcdスナップショットのリストをsyncするのにかかる総時間（秒単位）、成功/エラーのステータスによってラベル付けされています。

* タイプ:ヒストグラム
* ラベル: `*status*`

=== k3s_etcd_snapshot_reconcile_local_duration_seconds

ローカルスナップショットファイルのリストを取得するのにかかる総時間（秒単位）、成功/エラーのステータスによってラベル付けされています。

* タイプ:ヒストグラム
* ラベル: `*status*`

=== k3s_etcd_snapshot_reconcile_s3_duration_seconds

S3スナップショットファイルのリストを取得するのにかかる総時間（秒単位）、成功/エラーのステータスによってラベル付けされています。

* タイプ:ヒストグラム
* ラベル: `*status*`
