= k3s secrets-encrypt
:revdate: 2024-09-26
:page-revdate: {revdate}

K3s supports enabling secrets encryption at rest. For more information, see xref:security/secrets-encryption.adoc[Secrets Encryption].

== Secrets Encryption Tool

[IMPORTANT]
.Version Gate
====
Available as of https://github.com/k3s-io/k3s/releases/tag/v1.21.8%2Bk3s1[v1.21.8+k3s1]
====


K3s contains a CLI tool `secrets-encrypt`, which enables automatic control over the following:

* Disabling/Enabling secrets encryption
* Adding new encryption keys
* Rotating and deleting encryption keys
* Reencrypting secrets

[CAUTION]
====
Failure to follow proper procedure for rotating encryption keys can leave your cluster permanently corrupted. Proceed with caution.
====


=== New Encryption Key Rotation (Experimental)

[IMPORTANT]
.Version Gate
====
Available as of https://github.com/k3s-io/k3s/releases/tag/v1.28.1%2Bk3s1[v1.28.1+k3s1]. This new version of the tool utilized K8s https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/#configure-automatic-reloading[automatic config reloading] which is currently in beta. GA is expected in v1.29.0

For older releases, see <<_encryption_key_rotation_classic,Encryption Key Rotation Classic>>
====

[tabs,sync-group-id=se]
======
Single-Server::
+
--
To rotate secrets encryption keys on a single-server cluster:

. Start the K3s server with the flag `--secrets-encryption`
+
[NOTE]
====
Starting K3s without encryption and enabling it at a later time is currently _not_ supported.
====

. Rotate secrets encryption keys
+
----
k3s secrets-encrypt rotate-keys
----

. Wait for reencryption to finish. Watch the server logs, or wait for:
+
[,bash]
----
$ k3s secrets-encrypt status
Encryption Status: Enabled
Current Rotation Stage: reencrypt_finished
----
--

High-Availability::
+
--
To rotate secrets encryption keys on HA setups:

. Start up all three K3s servers with the `--secrets-encryption` flag. For brevity, the servers will be referred to as S1, S2, S3.
+
[NOTE]
====
Starting K3s without encryption and enabling it at a later time is currently _not_ supported.
====

. Rotate secrets encryption keys on S1
+
[,bash]
----
k3s secrets-encrypt rotate-keys
----

. Wait for reencryption to finish. Watch the server logs, or wait for:
+
[,bash]
----
$ k3s secrets-encrypt status
Encryption Status: Enabled
Current Rotation Stage: reencrypt_finished
----
+
[NOTE]
====
K3s will reencrypt ~5 secrets per second. Clusters with large # of secrets can take several minutes to reencrypt. You can track progress in the server logs.
====

. Restart K3s on S1 with same arguments. If running K3s as a service:
+
[,bash]
----
# If using systemd
systemctl restart k3s
# If using openrc
rc-service k3s restart
----

. Once S1 is up, restart K3s on S2 and S3
--
======

=== Encryption Key Rotation Classic

[tabs,sync-group-id=se]
======
Single-Server::
+
--
To rotate secrets encryption keys on a single-server cluster:

. Start the K3s server with the flag `--secrets-encryption`
+
[NOTE]
====
Starting K3s without encryption and enabling it at a later time is currently _not_ supported.
====

. Prepare
+
[,bash]
----
k3s secrets-encrypt prepare
----

. Kill and restart the K3s server with same arguments. If running K3s as a service:
+
[,bash]
----
# If using systemd
systemctl restart k3s
# If using openrc
rc-service k3s restart
----

. Rotate
+
[,bash]
----
k3s secrets-encrypt rotate
----

. Kill and restart the K3s server with same arguments
. Reencrypt
+
[NOTE]
====
K3s will reencrypt ~5 secrets per second. +
Clusters with large # of secrets can take several minutes to reencrypt.
====
+
[,bash]
----
k3s secrets-encrypt reencrypt
----
--

High-Availability::
+
--
The steps are the same for both embedded DB and external DB clusters.

To rotate secrets encryption keys on HA setups:

. Start up all three K3s servers with the `--secrets-encryption` flag. For brevity, the servers will be referred to as S1, S2, S3.
+
[NOTE]
====
* Starting K3s without encryption and enabling it at a later time is currently _not_ supported.
* While not required, it is recommended that you pick one server node from which to run the `secrets-encrypt` commands.
====
. Prepare on S1
+
[,bash]
----
k3s secrets-encrypt prepare
----

. Kill and restart S1 with same arguments. If running K3s as a service:
+
[,bash]
----
# If using systemd
systemctl restart k3s
# If using openrc
rc-service k3s restart
----

. Once S1 is up, kill and restart the S2 and S3
. Rotate on S1
+
[,bash]
----
k3s secrets-encrypt rotate
----

. Kill and restart S1 with same arguments
. Once S1 is up, kill and restart the S2 and S3
. Reencrypt on S1
+
[NOTE]
====
K3s will reencrypt ~5 secrets per second. +
Clusters with large # of secrets can take several minutes to reencrypt.
====
+
[,bash]
----
k3s secrets-encrypt reencrypt
----

. Kill and restart S1 with same arguments
. Once S1 is up, kill and restart the S2 and S3
--
======

=== Secrets Encryption Disable/Re-enable

[tabs,sync-group-id=se]
======
Single-Server::
+
--
After launching a server with `--secrets-encryption` flag, secrets encryption can be disabled.

To disable secrets encryption on a single-node cluster:

. Disable
+
[,bash]
----
k3s secrets-encrypt disable
----

. Kill and restart the K3s server with same arguments. If running K3s as a service:
+
[,bash]
----
# If using systemd
systemctl restart k3s
# If using openrc
rc-service k3s restart
----

. Reencrypt with flags
+
[,bash]
----
k3s secrets-encrypt reencrypt --force --skip
----

To re-enable secrets encryption on a single node cluster:

. Enable
+
[,bash]
----
k3s secrets-encrypt enable
----

. Kill and restart the K3s server with same arguments
. Reencrypt with flags
+
[,bash]
----
k3s secrets-encrypt reencrypt --force --skip
----
--

High-Availability::
+
--
After launching a HA cluster with `--secrets-encryption` flags, secrets encryption can be disabled.

[NOTE]
====
While not required, it is recommended that you pick one server node from which to run the `secrets-encrypt` commands.
====

For brevity, the three servers used in this guide will be referred to as S1, S2, S3.

To disable secrets encryption on a HA cluster:

. Disable on S1
+
[,bash]
----
k3s secrets-encrypt disable
----

. Kill and restart S1 with same arguments. If running K3s as a service:
+
[,bash]
----
# If using systemd
systemctl restart k3s
# If using openrc
rc-service k3s restart
----

. Once S1 is up, kill and restart the S2 and S3
. Reencrypt with flags on S1
+
[,bash]
----
k3s secrets-encrypt reencrypt --force --skip
----

To re-enable secrets encryption on a HA cluster:

. Enable on S1
+
[,bash]
----
k3s secrets-encrypt enable
----

. Kill and restart S1 with same arguments
. Once S1 is up, kill and restart the S2 and S3
. Reencrypt with flags on S1
+
[,bash]
----
k3s secrets-encrypt reencrypt --force --skip
----
--
======

=== Secrets Encryption Status

The secrets-encrypt tool includes a `status` command that displays information about the current status of secrets encryption on the node.

An example of the command on a single-server node:

[,bash]
----
$ k3s secrets-encrypt status
Encryption Status: Enabled
Current Rotation Stage: start
Server Encryption Hashes: All hashes match

Active  Key Type  Name
------  --------  ----
 *      AES-CBC   aescbckey
----

Another example on HA cluster, after rotating the keys, but before restarting the servers:

[,bash]
----
$ k3s secrets-encrypt status
Encryption Status: Enabled
Current Rotation Stage: rotate
Server Encryption Hashes: hash does not match between node-1 and node-2

Active  Key Type  Name
------  --------  ----
 *      AES-CBC   aescbckey-2021-12-10T22:54:38Z
        AES-CBC   aescbckey
----

Details on each section are as follows:

* *Encryption Status*: Displayed whether secrets encryption is disabled or enabled on the node
* *Current Rotation Stage*: Indicates the current rotation stage on the node. +
Stages are: `start`, `prepare`, `rotate`, `reencrypt_request`, `reencrypt_active`, `reencrypt_finished`
* *Server Encryption Hashes*: Useful for HA clusters, this indicates whether all servers are on the same stage with their local files. This can be used to identify whether a restart of servers is required before proceeding to the next stage. In the HA example above, node-1 and node-2 have different hashes, indicating that they currently do not have the same encryption configuration. Restarting the servers will sync up their configuration.
* *Key Table*: Summarizes information about the secrets encryption keys found on the node.
 ** *Active*: The "*" indicates which, if any, of the keys are currently used for secrets encryption. An active key is used by Kubernetes to encrypt any new secrets.
 ** *Key Type*: All keys using this tool are `AES-CBC` type. See more info https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/#providers[here.]
 ** *Name*: Name of the encryption key.
