= 卷和存储

在部署需要保​​留数据的应用时，你需要创建持久存储。持久存储允许你在运行应用的 pod 之外存储应用数据。即使运行应用的 pod 发生故障，这种存储方式也能让你保留应用数据。

持久卷 (PV) 是 Kubernetes 集群中的一块存储，而持久卷声明 (PVC) 是对存储的请求。有关 PV 和 PVC 工作原理的详细信息，请参阅 https://kubernetes.io/docs/concepts/storage/volumes/[Kubernetes 存储相关的官方文档]。

K3s, as a compliant Kubernetes distribution, uses the https://github.com/container-storage-interface/spec/blob/master/spec.md[Container Storage Interface (CSI)] and https://kubernetes.io/docs/tasks/administer-cluster/running-cloud-controller/[Cloud Provider Interface (CPI)] to manage persistent storage.

本文介绍如何使用本地存储提供程序或 <<_设置_longhorn,Longhorn>> 设置持久存储。

[#_setting_up_the_local_storage_provider]
== 设置本地存储提供程序

K3s 自带 Rancher 的 Local Path Provisioner，这使得能够使用各自节点上的本地存储来开箱即用地创建持久卷声明。下面是一个简单的例子。有关更多信息，请参阅link:https://github.com/rancher/local-path-provisioner/blob/master/README.md#usage[官方文档]。

创建一个 hostPath 支持的持久卷声明和一个使用它的 Pod：

=== pvc.yaml

[,yaml]
----
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-path-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
----

=== pod.yaml

[,yaml]
----
apiVersion: v1
kind: Pod
metadata:
  name: volume-test
  namespace: default
spec:
  containers:
  - name: volume-test
    image: nginx:stable-alpine
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: volv
      mountPath: /data
    ports:
    - containerPort: 80
  volumes:
  - name: volv
    persistentVolumeClaim:
      claimName: local-path-pvc
----

应用 yaml：

[,bash]
----
kubectl create -f pvc.yaml
kubectl create -f pod.yaml
----

确认创建了 PV 和 PVC：

[,bash]
----
kubectl get pv
kubectl get pvc
----

状态都应该是 Bound。

== 设置 Longhorn

[CAUTION]
====
Longhorn 不支持 ARM32。
====


K3s 支持 https://github.com/longhorn/longhorn[Longhorn]，这是用于 Kubernetes 的开源分布式块存储系统。

下面是一个简单的例子。有关详细信息，请参阅link:https://documentation.suse.com/cloudnative/storage/{longhorn_docs_version}/en/longhorn-documentation.html[官方文档]。

应用 longhorn.yaml 来安装 Longhorn：

[,bash]
----
kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/v1.8.1/deploy/longhorn.yaml
----

Longhorn 将安装在命名空间 `longhorn-system` 中。

Create a persistent volume claim and a pod to utilize it:

=== pvc.yaml

[,yaml]
----
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-volv-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
----

=== pod.yaml

[,yaml]
----
apiVersion: v1
kind: Pod
metadata:
  name: volume-test
  namespace: default
spec:
  containers:
  - name: volume-test
    image: nginx:stable-alpine
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: volv
      mountPath: /data
    ports:
    - containerPort: 80
  volumes:
  - name: volv
    persistentVolumeClaim:
      claimName: longhorn-volv-pvc
----

应用 yaml 来创建 PVC 和 Pod：

[,bash]
----
kubectl create -f pvc.yaml
kubectl create -f pod.yaml
----

确认创建了 PV 和 PVC：

[,bash]
----
kubectl get pv
kubectl get pvc
----

状态都应该是 Bound。
