= Mises à niveau
:page-languages: [en, ja, ko, zh]
:revdate: 2024-09-11
:page-revdate: {revdate}

== Mettre à niveau votre grappe K3s

xref:upgrades/manual.adoc[Les mises à niveau manuelles] décrivent plusieurs techniques pour mettre à niveau votre grappe manuellement. Il peut également servir de base pour effectuer des mises à niveau via des outils tiers d'infrastructure en tant que code comme https://www.terraform.io/[Terraform].

xref:upgrades/automated.adoc[Les mises à niveau automatisées] décrivent comment effectuer des mises à niveau automatisées natives de Kubernetes en utilisant https://github.com/rancher/system-upgrade-controller[system-upgrade-controller] de Rancher.

== Avertissements spécifiques à la version

* *Traefik\&nbsp;:* Si Traefik n'est pas désactivé, les versions K3s 1.20 et antérieures installeront Traefik v1, tandis que les versions K3s 1.21 et ultérieures installeront Traefik v2, si v1 n'est pas déjà présent. Pour passer de l'ancienne version Traefik v1 à Traefik v2, veuillez consulter la https://doc.traefik.io/traefik/migrate/v1-to-v2/[documentation de Traefik] et utiliser l'https://github.com/traefik/traefik-migration-tool[outil de migration].
* *Données de démarrage K3s\&nbsp;:* Si vous utilisez K3s dans une configuration HA avec un magasin de données SQL externe, et que vos nœuds de serveur (plan de contrôle) n'ont pas été démarrés avec le drapeau `--token` CLI, vous ne pourrez plus ajouter de serveurs K3s supplémentaires à la grappe sans spécifier le token. Assurez-vous de conserver une copie de ce token, car il est requis lors de la restauration à partir d'une sauvegarde. Auparavant, K3s n'imposait pas l'utilisation d'un token lors de l'utilisation de magasins de données SQL externes.
 ** Les versions concernées sont <= v1.19.12+k3s1, v1.20.8+k3s1, v1.21.2+k3s1 ; les versions corrigées sont v1.19.13+k3s1, v1.20.9+k3s1, v1.21.3+k3s1.
 ** Vous pouvez récupérer la valeur du token à partir de n'importe quel serveur déjà joint à la grappe comme suit :
+
[,bash]
----
cat /var/lib/rancher/k3s/server/token
----
