= K3sのアンインストール
:page-languages: [en, ja, ko, zh]
:revdate: 2024-12-05
:page-revdate: {revdate}

[CAUTION]
====
Uninstalling K3s may cause data loss!
====

インストールスクリプトを使用してK3sをインストールした場合、インストール中にK3sをアンインストールするためのスクリプトが生成されました。

Running the uninstall script stops K3s and all running pods, and deletes the local cluster datastore, xref:storage.adoc#_setting_up_the_local_storage_provider[Local Storage] Persistent Volume data, node configuration, and all of the scripts and CLI tools.

It does not remove any data from external datastores, or created by pods using external Kubernetes Persistent Volumes.


アンインストール後にノードを既存のクラスターに再参加させる予定がある場合は、ノードのパスワードシークレットが削除されるように、クラスターからノードを削除することを忘れないでください。詳細については、xref:architecture.adoc#_how_agent_node_registration_works[ノード登録]のドキュメントを参照してください。

== サーバーのアンインストール

サーバーノードからK3sをアンインストールするには、次のコマンドを実行します:

[,bash]
----
/usr/local/bin/k3s-uninstall.sh
----

== エージェントのアンインストール

エージェントノードからK3sをアンインストールするには、次のコマンドを実行します:

[,bash]
----
/usr/local/bin/k3s-agent-uninstall.sh
----
