= Métricas
:page-languages: [en, ja, ko, zh]
:revdate: 2025-09-16
:page-revdate: {revdate}

O K3s fornece métricas para monitorar a saúde e o desempenho do cluster.

A maioria das métricas é fornecida por componentes individuais. Consulte a documentação específica de cada componente a seguir para mais informações:

* https://coredns.io/plugins/metrics/[métricas do coredns]
* https://etcd.io/docs/v3.5/metrics/[métricas do etcd]

Métricas adicionais podem ser fornecidas por outros componentes. Consulte a documentação do projeto upstream para quaisquer componentes não listados acima.

== Métricas do Supervisor

Quando o K3s é iniciado com `supervisor-metrics: true`, as métricas são expostas pelo processo K3s e podem ser acessadas através do endpoint `/metrics` em cada nó na porta `6443`:

[,sh]
----
kubectl get --server https://NODENAME:6443 --raw /metrics
----

O processo supervisor do K3s expõe as seguintes métricas:

* Métricas de Gerenciamento do Cluster K3s
* https://github.com/rancher/lasso/blob/main/README.md#lasso-controller[métricas do controlador Lasso]
* https://github.com/kubernetes/client-go/blob/master/README.md[métricas do cliente Kubernetes e da fila de trabalho]
* https://kubernetes.io/docs/reference/instrumentation/node-metrics/[Métricas do Nó Kubernetes]
* https://kubernetes.io/docs/reference/instrumentation/metrics/[Métricas de Componentes Kubernetes]
* https://pkg.go.dev/runtime/metrics#hdr-Supported_metrics[métricas do runtime Go]

Se o registro embutido do K3s estiver habilitado, o processo supervisor do K3s também expõe as seguintes métricas:

* https://spegel.dev/docs/metrics/[métricas do Spegel]
* https://github.com/libp2p/go-libp2p/blob/master/README.md[métricas do libp2p]

O K3s executa todos os componentes do Kubernetes no processo principal do K3s. Como o Kubernetes usa um único registro de métricas do Prometheus por processo, as métricas de todos os componentes estão disponíveis através de todos os endpoints de métricas expostos. Se você coletar todos os endpoints de métricas individuais, pode descobrir que está coletando métricas duplicadas. É necessário coletar apenas um único endpoint de métricas do K3s para obter métricas de todos os componentes do Kubernetes incorporados.

== Métricas de Gerenciamento do Cluster K3s

=== k3s_certificate_expiration_seconds

Tempo de vida restante em segundos do certificado, rotulado pelo assunto do certificado e usos.

* Tipo: Medidor
* Rótulos: `*subject*`, `*usage*`

=== k3s_loadbalancer_server_connections

Contagem de conexões atuais ao servidor do balanceador de carga, rotulada pelo nome do balanceador de carga e endereço do servidor.

* Tipo: Medidor
* Rótulos: `*name*`, `*server*`

=== k3s_loadbalancer_server_health

Estado de saúde atual dos servidores de backend do balanceador de carga, rotulado pelo nome do balanceador de carga e endereço do servidor.

O estado é um enum de 0=INVALID, 1=FAILED, 2=STANDBY, 3=UNCHECKED, 4=RECOVERING, 5=HEALTHY, 6=PREFERRED, 7=ACTIVE.

* Tipo: Medidor
* Rótulos: `*name*`, `*server*`

=== k3s_loadbalancer_dial_duration_seconds

Tempo em segundos necessário para estabelecer uma conexão com um servidor de backend, rotulado pelo nome do balanceador de carga e status de sucesso/falha.

* Tipo: Histograma
* Rótulos: `*name*`, `*status*`

=== k3s_etcd_snapshot_save_duration_seconds

Tempo total em segundos necessário para completar o processo de instantâneo do etcd, rotulado pelo status de sucesso/falha.

* Tipo: Histograma
* Rótulos: `*status*`

=== k3s_etcd_snapshot_save_local_duration_seconds

Tempo total em segundos necessário para salvar um arquivo instantâneo local, rotulado pelo status de sucesso/falha.

* Tipo: Histograma
* Rótulos: `*status*`

=== k3s_etcd_snapshot_save_s3_duration_seconds

Tempo total em segundos necessário para fazer upload de um arquivo instantâneo para o S3, rotulado pelo status de sucesso/falha.

* Tipo: Histograma
* Rótulos: `*status*`

=== k3s_etcd_snapshot_reconcile_duration_seconds

Tempo total em segundos necessário para sincronizar a lista de instantâneos do etcd, rotulado pelo status de sucesso/falha.

* Tipo: Histograma
* Rótulos: `*status*`

=== k3s_etcd_snapshot_reconcile_local_duration_seconds

Tempo total em segundos necessário para listar arquivos instantâneos locais, rotulado pelo status de sucesso/falha.

* Tipo: Histograma
* Rótulos: `*status*`

=== k3s_etcd_snapshot_reconcile_s3_duration_seconds

Tempo total em segundos necessário para listar arquivos instantâneos do S3, rotulado pelo status de sucesso/falha.

* Tipo: Histograma
* Rótulos: `*status*`
