= FAQ

The FAQ is updated periodically and designed to answer the questions our users most frequently ask about K3s.

== Is K3s a suitable replacement for Kubernetes?

K3s is a CNCF-certified Kubernetes distribution, and can do everything required of a standard Kubernetes cluster. It is just a more lightweight version. See the xref:./introduction.adoc[main] docs page for more details.

== How can I use my own Ingress instead of Traefik?

Simply start K3s server with `--disable=traefik` and deploy your ingress.

== Does K3s support Windows?

At this time K3s does not natively support Windows, however we are open to the idea in the future.

== What exactly are Servers and Agents?

For a breakdown on the components that make up a server and agent, see the xref:./architecture.adoc[Architecture page].

== How can I build from source?

Please reference the K3s https://github.com/k3s-io/k3s/blob/master/BUILDING.md[BUILDING.md] with instructions.

== Where are the K3s logs?

The location of K3s logs will vary depending on how you run K3s and the node's OS.

* When run from the command line, logs are sent to stdout and stderr.
* When running under openrc, logs will be created at `/var/log/k3s.log`.
* When running under Systemd, logs will be sent to Journald and can be viewed using `journalctl -u k3s`.
* Pod logs can be found at `/var/log/pods`.
* Containerd logs can be found at `/var/lib/rancher/k3s/agent/containerd/containerd.log`.

You can generate more detailed logs by using the `--debug` flag when starting K3s (or `debug: true` in the configuration file).

Kubernetes uses a logging framework known as `klog`, which uses a single logging configuration for all components within a process.
Since K3s runs all Kubernetes components within a single process, it is not possible to configure different log levels or destinations for individual Kubernetes components.
Use of the `-v=<level>` or `--vmodule=<module>=<level>` component args will likely not have the desired effect.

See xref:./advanced.adoc#_additional-logging-sources[Additional Logging Sources] for even more log options.

== Can I run K3s in Docker?

Yes, there are multiple ways to run K3s in Docker. See xref:./advanced.adoc#_running-k3s-in-docker[Advanced Options] for more details.

== What is the difference between K3s Server and Agent Tokens?

For more information on managing K3s join tokens, see the xref:./cli/token.adoc[`k3s token` command documentation].

== How compatible are different versions of K3s?

In general, the https://kubernetes.io/docs/setup/release/version-skew-policy/[Kubernetes version skew policy] applies.

In short, servers can be newer than agents, but agents cannot be newer than servers.

== I'm having an issue, where can I get help?

If you are having an issue with deploying K3s, you should:

. Check the xref:./known-issues.adoc[Known Issues] page.
. Check that you have resolved any xref:./installation/requirements.adoc#_operating-systems[Additional OS Preparation]. Run `k3s check-config` and ensure that it passes.
. Search the K3s https://github.com/k3s-io/k3s/issues[Issues] and https://github.com/k3s-io/k3s/discussions[Discussions] for one that matches your problem.
. Join the https://slack.rancher.io/[Rancher Slack] K3s channel to get help.
. Submit a https://github.com/k3s-io/k3s/issues/new/choose[New Issue] on the K3s Github describing your setup and the issue you are experiencing.
