= {product-name}
:revdate: 2024-10-23
:page-revdate: {revdate}
:page-role: -toc

K3s is an official https://www.cncf.io[CNCF] sandbox project that delivers a lightweight yet powerful certified Kubernetes distribution designed for production workloads across resource-restrained, remote locations or on IoT devices. When used with SUSE® Rancher Prime, K3s is simple to install, lightweight yet high availability Kubernetes distribution that can be easily managed within the Rancher orchestration platform.

== Key Features

* Distributed as a single binary or minimal container image.
* Lightweight datastore based on sqlite3 as the default storage backend. etcd3, MySQL, and Postgres are also available.
* Wrapped in simple launcher that handles a lot of the complexity of TLS and options.
* Secure by default with reasonable defaults for lightweight environments.
* Operation of all Kubernetes control plane components is encapsulated in a single binary and process, allowing K3s to automate and manage complex cluster operations like distributing certificates.
* External dependencies have been minimized; the only requirements are a modern kernel and cgroup mounts.
* Packages the required dependencies for easy "batteries-included" cluster creation:
 ** containerd / cri-dockerd container runtime (CRI)
 ** Flannel Container Network Interface (CNI)
 ** CoreDNS Cluster DNS
 ** Traefik Ingress controller
 ** ServiceLB Load-Balancer controller
 ** Kube-router Network Policy controller
 ** Local-path-provisioner Persistent Volume controller
 ** Spegel distributed container image registry mirror
 ** Host utilities (iptables, socat, etc)

== Great for:

* Edge
* Homelab
* Internet of Things (IoT)
* Continuous Integration (CI)
* Development
* Single board computers (ARM)
* Air-gapped environments
* Embedded K8s
* Situations where a PhD in K8s clusterology is infeasible
