= Quick-Start Guide
:page-languages: [en, ja, ko, zh]
:revdate: 2026-03-03
:page-revdate: {revdate}

This guide will help you quickly launch a cluster with default options. Make sure your nodes meet the xref:installation/requirements.adoc[requirements] before proceeding.

* Consult the xref:installation/installation.adoc[Installation] page for greater detail on installing and configuring K3s.
* For information on how K3s components work together, refer to the xref:architecture.adoc[Architecture] page.
* If you are new to Kubernetes, the https://kubernetes.io/docs/tutorials/kubernetes-basics/[official Kubernetes docs] have great tutorials covering basics that all cluster administrators should be familiar with.

[IMPORTANT]
====
You can use any K3s Prime version listed on the Prime Artifacts URL for the assets mentioned in these steps. To learn more about the Prime Artifacts URL, see our https://scc.suse.com/rancher-docs/rancherprime/latest/en/reference-guide.html#prime-artifacts-url[Prime-only documentation]. Authentication is required. Use your https://scc.suse.com/home[SUSE Customer Center (SCC)] credentials to log in.
====


== Install Script

{k3s-product-name} provides an installation script that is a convenient way to install it as a service on systemd or openrc based systems. This script is available at https://get.k3s.io. To install {k3s-product-name} using this method, do the following:

Run the installer, where `INSTALL_K3S_ARTIFACT_URL` is the https://scc.suse.com/rancher-docs/rancherprime/latest/en/reference-guide.html#prime-artifacts-url[Prime Artifacts URL] and `INSTALL_K3S_CHANNEL` is a release channel you can subscribe to and defaults to `stable`. In this example, `INSTALL_K3S_CHANNEL="latest"` gives you the latest version of {k3s-product-name}.

[,bash]
----
curl -sfL https://get.k3s.io | INSTALL_K3S_ARTIFACT_URL=<PRIME-ARTIFACTS-URL>/k3s INSTALL_K3S_CHANNEL="latest" sh -
----
If you want to specify a version, set the `INSTALL_RKE2_VERSION` environment variable:

[,bash]
----
curl -sfL https://get.k3s.io/ | sudo INSTALL_K3S_ARTIFACT_URL=<PRIME-ARTIFACTS-URL>/k3s INSTALL_K3S_VERSION="<VERSION>" sh -
----

After running this installation:

* The K3s service will be configured to automatically restart after node reboots or if the process crashes or is killed
* Additional utilities will be installed, including `kubectl`, `crictl`, `ctr`, `k3s-killall.sh`, and `k3s-uninstall.sh`
* A https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/[kubeconfig] file will be written to `/etc/rancher/k3s/k3s.yaml` and the kubectl installed by {k3s-product-name} will automatically use it

A single-node server installation is a fully-functional Kubernetes cluster, including all the datastore, control-plane, kubelet, and container runtime components necessary to host workload pods. It is not necessary to add additional server or agents nodes, but you may want to do so to add additional capacity or redundancy to your cluster.

To install additional agent nodes and add them to the cluster, run the installation script with the `K3S_URL` and `K3S_TOKEN` environment variables. Here is an example showing how to join an agent:

[,bash]
----
curl -sfL https://get.k3s.io | INSTALL_K3S_ARTIFACT_URL=<PRIME-ARTIFACTS-URL>/k3s K3S_URL=https://myserver:6443 K3S_TOKEN=mynodetoken sh -
----

Setting the `K3S_URL` parameter causes the installer to configure K3s as an agent, instead of a server. The K3s agent will register with the K3s server listening at the supplied URL. The value to use for `K3S_TOKEN` is stored at `/var/lib/rancher/k3s/server/node-token` on your server node.

[NOTE]
====
Each machine must have a unique hostname. If your machines do not have unique hostnames, pass the `K3S_NODE_NAME` environment variable and provide a value with a valid and unique hostname for each node.
====


If you are interested in having more server nodes, see the xref:datastore/ha-embedded.adoc[High Availability Embedded etcd] and xref:datastore/ha.adoc[High Availability External DB] pages for more information.
