= 常见问题
:page-languages: [en, ja, ko, zh]
:revdate: 2024-09-11
:page-revdate: {revdate}

常见问题解答定期更新，旨在回答用户关于K3s最常见的问题。

== K3s是Kubernetes的合适替代品吗？

K3s是CNCF认证的Kubernetes发行版，可以完成标准Kubernetes集群所需的所有功能。它只是一个更轻量级的版本。有关更多详细信息，请参阅xref:introduction.adoc[主]文档页面。

== 我如何使用自己的Ingress而不是Traefik？

只需使用`--disable=traefik`启动K3s服务器并部署您的ingress。

== K3s支持Windows吗？

目前K3s不原生支持Windows，但我们在未来对此持开放态度。

== 服务器和代理到底是什么？

有关构成服务器和代理的组件的详细信息，请参阅xref:architecture.adoc[架构页面]。

== 我如何从源代码构建？

请参考K3s https://github.com/k3s-io/k3s/blob/main/BUILDING.md[BUILDING.md]中的说明。

== K3s日志在哪里？

K3s日志的位置将根据您运行K3s的方式和节点的操作系统而有所不同。

* 从命令行运行时，日志会发送到stdout和stderr。
* 在openrc下运行时，日志将创建在`/var/log/k3s.log`。
* 在Systemd下运行时，日志将发送到Journald，并可以使用`journalctl -u k3s`查看。
* Pod日志可以在`/var/log/pods`找到。
* Containerd日志可以在`/var/lib/rancher/k3s/agent/containerd/containerd.log`找到。

您可以在启动K3s时使用`--debug`标志（或在配置文件中使用`debug: true`）来生成更详细的日志。

Kubernetes 使用一个称为 `klog` 的日志框架，该框架为进程中的所有组件使用单一的日志配置。
由于 K3s 在单个进程中运行所有 Kubernetes 组件，因此无法为单个 Kubernetes 组件配置不同的日志级别或目标。
使用 `-v=<level>` 或 `--vmodule=<module>=<level>` 组件参数可能不会产生预期的效果。

请参见 xref:advanced.adoc#_additional_logging_sources[附加日志源] 以获取更多日志选项。

== 我可以在 Docker 中运行 K3s 吗？

是的，有多种方法可以在 Docker 中运行 K3s。请参见 xref:advanced.adoc#_running_k3s_in_docker[高级选项] 以获取更多详细信息。

== K3s 服务器和代理令牌之间有什么区别？

有关管理 K3s 加入令牌的更多信息，请参见 xref:cli/token.adoc[`k3s token` 命令文档]。

== 不同版本的 K3s 兼容性如何？

一般来说，适用 https://kubernetes.io/docs/setup/release/version-skew-policy/[Kubernetes 版本偏差策略]。

简而言之，服务器可以比代理更新，但代理不能比服务器更新。

== 我遇到了一个问题，我可以在哪里获得帮助？

如果您在部署 K3s 时遇到问题，您应该：

. 检查 xref:known-issues.adoc[已知问题] 页面。
. 检查您是否已解决任何 xref:installation/requirements.adoc#_operating_systems[附加操作系统准备]。运行 `k3s check-config` 并确保它通过。
. 在 K3s https://github.com/k3s-io/k3s/issues[问题] 和 https://github.com/k3s-io/k3s/discussions[讨论] 中搜索与您的问题匹配的内容。
. 加入 https://slack.rancher.io/[Rancher Slack] K3s 频道以获取帮助。
. 在 K3s Github 上提交一个 https://github.com/k3s-io/k3s/issues/new/choose[新问题]，描述您的设置和您遇到的问题。
