= Actualizaciones
:page-languages: [en, ja, ko, zh]
:revdate: 2024-09-11
:page-revdate: {revdate}

== Actualizando tu clúster K3s

xref:upgrades/manual.adoc[Las Actualizaciones Manuales] describe varias técnicas para actualizar tu clúster manualmente. También se puede utilizar como base para actualizar a través de herramientas de infraestructura como código de terceros como https://www.terraform.io/[Terraform].

xref:upgrades/automated.adoc[Actualizaciones Automatizadas] describe cómo realizar actualizaciones automatizadas nativas de Kubernetes utilizando https://github.com/rancher/system-upgrade-controller[system-upgrade-controller] de Rancher.

== Advertencias específicas de la versión

* *Traefik:* Si Traefik no está deshabilitado, las versiones de K3s 1.20 y anteriores instalarán Traefik v1, mientras que las versiones de K3s 1.21 y posteriores instalarán Traefik v2, si v1 no está ya presente. Para actualizar de la antigua Traefik v1 a Traefik v2, consulta la https://doc.traefik.io/traefik/migrate/v1-to-v2/[documentación de Traefik] y utiliza la https://github.com/traefik/traefik-migration-tool[herramienta de migración].
* *Datos de inicio de K3s:* Si estás utilizando K3s en una configuración HA con un almacén de datos SQL externo, y tus nodos de servidor (control-plane) no se iniciaron con la opción de línea de comandos `--token`, ya no podrás añadir servidores K3s adicionales al clúster sin especificar el token. Asegúrate de conservar una copia de este token, ya que es necesario al restaurar desde una copia de seguridad. Anteriormente, K3s no imponía el uso de un token al utilizar almacenes de datos SQL externos.
 ** Las versiones afectadas son <= v1.19.12+k3s1, v1.20.8+k3s1, v1.21.2+k3s1; las versiones corregidas son v1.19.13+k3s1, v1.20.9+k3s1, v1.21.3+k3s1.
 ** Puedes recuperar el valor del token de cualquier servidor que ya esté unido al clúster de la siguiente manera:
+
[,bash]
----
cat /var/lib/rancher/k3s/server/token
----
