= バックアップとリストア
:revdate: 2024-09-11
:page-revdate: {revdate}

K3sのバックアップとリストアの方法は、使用するデータストアの種類によって異なります。

[CAUTION]
====
データストア自体のバックアップに加えて、サーバートークンファイルを``/var/lib/rancher/k3s/server/token``にバックアップする必要があります。
バックアップからリストアする際には、このファイルをリストアするか、その値を``--token``オプションに渡す必要があります。
リストア時に同じトークン値を使用しない場合、スナップショットは使用できません。トークンはデータストア内の機密データを暗号化するために使用されるからです。
====


== SQLiteでのバックアップとリストア

SQLiteデータストアのバックアップやリストアには特別なコマンドは必要ありません。

* SQLiteデータストアをバックアップするには、``/var/lib/rancher/k3s/server/db/``のコピーを取ります。
* SQLiteデータストアをリストアするには、``/var/lib/rancher/k3s/server/db``の内容（および上記のトークン）をリストアします。

== 外部データストアでのバックアップとリストア

外部データストアが使用されている場合、バックアップとリストアの操作はK3sの外部で行われます。データベース管理者は外部データベースをバックアップするか、スナップショットやダンプからリストアする必要があります。

データベースが定期的にスナップショットを取るように設定することをお勧めします。

データベースのスナップショットを取る方法やそれらからデータベースをリストアする方法については、公式のデータベースドキュメントを参照してください：

* https://dev.mysql.com/doc/refman/8.0/en/replication-snapshot-method.html[公式MySQLドキュメント]
* https://www.postgresql.org/docs/8.3/backup-dump.html[公式PostgreSQLドキュメント]
* https://etcd.io/docs/latest/op-guide/recovery/[公式etcdドキュメント]

== 組み込みetcdデータストアでのバックアップとリストア

組み込みetcdデータストアのバックアップとリストア操作については、xref:cli/etcd-snapshot.adoc[``k3s etcd-snapshot``コマンドのドキュメント]を参照してください。
