= クイックスタートガイド
:page-languages: [en, ja, ko, zh]
:revdate: 2026-03-03
:page-revdate: {revdate}

このガイドは、デフォルトオプションでクラスターを迅速に立ち上げるのに役立ちます。進む前に、ノードがxref:installation/requirements.adoc[要件]を満たしていることを確認してください。

* K3sのインストールと構成に関する詳細は、xref:installation/installation.adoc[インストール]ページを参照してください。
* K3sコンポーネントがどのように連携して動作するかについては、xref:architecture.adoc[アーキテクチャ]ページを参照してください。
* Kubernetesが初めての場合、https://kubernetes.io/docs/tutorials/kubernetes-basics/[公式Kubernetesドキュメント]には、すべてのクラスター管理者が知っておくべき基本をカバーした素晴らしいチュートリアルがあります。

[IMPORTANT]
====
これらの手順で言及されている資産については、Prime Artifacts URLにリストされている任意のK3s Primeバージョンを使用できます。Prime Artifacts URLの詳細については、https://scc.suse.com/rancher-docs/rancherprime/latest/en/reference-guide.html#prime-artifacts-url[Prime専用ドキュメント]をご覧ください。認証が必要です。ログインするには、https://scc.suse.com/home[SUSEカスタマーセンター（SCC）]の資格情報を使用してください。
====


== インストールスクリプト

{k3s-product-name}は、systemdまたはopenrcベースのシステムにサービスとしてインストールするための便利なインストールスクリプトを提供します。このスクリプトはhttps://get.k3s.io.で入手できます。この方法で{k3s-product-name}をインストールするには、次の手順を実行してください：

インストーラーを実行します。ここで、`INSTALL_K3S_ARTIFACT_URL`はhttps://scc.suse.com/rancher-docs/rancherprime/latest/en/reference-guide.html#prime-artifacts-url[Prime Artifacts URL]で、`INSTALL_K3S_CHANNEL`は購読できるリリースチャネルで、デフォルトは`stable`です。この例では、`INSTALL_K3S_CHANNEL="latest"`が{k3s-product-name}の最新バージョンを提供します。

[,bash]
----
curl -sfL https://get.k3s.io | INSTALL_K3S_ARTIFACT_URL=<PRIME-ARTIFACTS-URL>/k3s INSTALL_K3S_CHANNEL="latest" sh -
----
バージョンを指定したい場合は、`INSTALL_RKE2_VERSION`環境変数を設定してください：

[,bash]
----
curl -sfL https://get.k3s.io/ | sudo INSTALL_K3S_ARTIFACT_URL=<PRIME-ARTIFACTS-URL>/k3s INSTALL_K3S_VERSION="<VERSION>" sh -
----

このインストールを実行した後：

* K3sサービスは、ノードの再起動後やプロセスがクラッシュまたは終了した場合に自動的に再起動するように構成されます。
* `kubectl`、`crictl`、`ctr`、`k3s-killall.sh`、および`k3s-uninstall.sh`を含む追加のユーティリティがインストールされます。
* https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/[kubeconfig] ファイルが `/etc/rancher/k3s/k3s.yaml` に書き込まれ、{k3s-product-name} によってインストールされた kubectl が自動的にそれを使用します。

シングルノードサーバーのインストールは、ワークロードポッドをホストするために必要なすべてのデータストア、コントロールプレーン、kubelet、およびコンテナランタイムコンポーネントを含む完全機能の Kubernetes クラスターです。追加のサーバーやエージェントノードを追加する必要はありませんが、クラスターに追加の容量や冗長性を加えるために追加したい場合があります。

追加のエージェントノードをインストールし、クラスターに追加するには、`K3S_URL` および `K3S_TOKEN` 環境変数を使用してインストールスクリプトを実行します。エージェントをクラスターに参加させる方法の例は次のとおりです。

[,bash]
----
curl -sfL https://get.k3s.io | INSTALL_K3S_ARTIFACT_URL=<PRIME-ARTIFACTS-URL>/k3s K3S_URL=https://myserver:6443 K3S_TOKEN=mynodetoken sh -
----

`K3S_URL` パラメータを設定すると、インストーラーは K3s をサーバーではなくエージェントとして構成します。K3s エージェントは、提供された URL でリスンしている K3s サーバーに登録します。`K3S_TOKEN` に使用する値は、サーバーノードの `/var/lib/rancher/k3s/server/node-token` に保存されています。

[NOTE]
====
各マシンには一意のホスト名が必要です。マシンに一意のホスト名がない場合は、`K3S_NODE_NAME` 環境変数を渡し、各ノードに対して有効で一意のホスト名の値を提供してください。
====


サーバーノードをさらに追加したい場合は、xref:datastore/ha-embedded.adoc[高可用性組み込みetcd] および xref:datastore/ha.adoc[高可用性外部DB] ページを参照して、詳細情報をご覧ください。
