= FAQ

FAQは定期的に更新され、K3sに関してユーザーが最も頻繁に尋ねる質問に答えるために設計されています。

== K3sはKubernetesの代替として適していますか？

K3sはCNCF認定のKubernetesディストリビューションであり、標準的なKubernetesクラスターに必要なすべてのことを実行できます。ただし、より軽量なバージョンです。詳細についてはxref:./introduction.adoc[メイン]ドキュメントページを参照してください。

== Traefikの代わりに自分のIngressを使用するにはどうすればよいですか？

単にK3sサーバーを``--disable=traefik``オプションで起動し、Ingressをデプロイしてください。

== K3sはWindowsをサポートしていますか？

現時点ではK3sはネイティブにWindowsをサポートしていませんが、将来的にはその可能性を検討しています。

== サーバーとエージェントとは具体的に何ですか？

サーバーとエージェントを構成するコンポーネントの詳細については、xref:./architecture.adoc[アーキテクチャページ]を参照してください。

== ソースからビルドするにはどうすればよいですか？

K3sのhttps://github.com/k3s-io/k3s/blob/master/BUILDING.md[BUILDING.md]を参照してください。

== K3sのログはどこにありますか？

K3sのログの場所は、K3sの実行方法やノードのOSによって異なります。

* コマンドラインから実行する場合、ログはstdoutとstderrに送信されます。
* openrcで実行する場合、ログは``/var/log/k3s.log``に作成されます。
* Systemdで実行する場合、ログはJournaldに送信され、``journalctl -u k3s``で表示できます。
* Podのログは``/var/log/pods``にあります。
* Containerdのログは``/var/lib/rancher/k3s/agent/containerd/containerd.log``にあります。

K3sを起動する際に``--debug``フラグ（または設定ファイルで``debug: true``）を使用すると、より詳細なログを生成できます。

Kubernetesは``klog``というロギングフレームワークを使用しており、プロセス内のすべてのコンポーネントに対して単一のロギング設定を使用します。K3sはすべてのKubernetesコンポーネントを単一のプロセス内で実行するため、個々のKubernetesコンポーネントに対して異なるログレベルや出力先を設定することはできません。``-v=<level>``や``--vmodule=<module>=<level>``のコンポーネント引数を使用しても、期待通りの効果は得られない可能性があります。

さらに多くのログオプションについては、xref:./advanced.adoc#_additional-logging-sources[追加のログソース]を参照してください。

== DockerでK3sを実行できますか？

はい、DockerでK3sを実行する方法はいくつかあります。詳細についてはxref:./advanced.adoc#_running-k3s-in-docker[高度なオプション]を参照してください。

== K3sサーバーとエージェントトークンの違いは何ですか？

K3sの参加トークンの管理に関する詳細は、xref:./cli/token.adoc[``k3s token``コマンドのドキュメント]を参照してください。

== 異なるバージョンのK3sの互換性はどの程度ですか？

一般的に、https://kubernetes.io/docs/setup/release/version-skew-policy/[Kubernetesのバージョンスキューポリシー]が適用されます。

簡単に言えば、サーバーはエージェントより新しいバージョンであることができますが、エージェントはサーバーより新しいバージョンであってはなりません。

== 問題が発生した場合、どこで助けを得られますか？

K3sのデプロイに問題がある場合は、以下を行ってください：

1) xref:./known-issues.adoc[既知の問題]ページを確認してください。

2) xref:./installation/requirements.adoc#_operating-systems[追加のOS準備]が解決されていることを確認してください。``k3s check-config``を実行し、パスすることを確認してください。

3) K3sのhttps://github.com/k3s-io/k3s/issues[Issues]およびhttps://github.com/k3s-io/k3s/discussions[Discussions]で、問題に一致するものを検索してください。

// lint disable no-dead-urls

4) https://slack.rancher.io/[Rancher Slack]のK3sチャンネルに参加して助けを求めてください。

5) K3s Githubにhttps://github.com/k3s-io/k3s/issues/new/choose[新しいIssue]を提出し、セットアップと発生している問題を説明してください。
