= k3s secrets-encrypt
:page-languages: [en, ja, ko, zh]
:revdate: 2026-01-05
:page-revdate: {revdate}

K3s suporta a habilitação da criptografia de segredos em repouso. Para mais informações, veja xref:security/secrets-encryption.adoc[Criptografia de Segredos].

== Ferramenta de Criptografia de Segredos

[IMPORTANT]
.Gatilho de Versão
====
Disponível a partir de https://github.com/k3s-io/k3s/releases/tag/v1.21.8%2Bk3s1[v1.21.8+k3s1]
====


K3s contém uma ferramenta CLI `secrets-encrypt`, que permite controle automático sobre o seguinte:

* Desabilitar/Habilitar criptografia de segredos
* Adicionar novas chaves de criptografia de segredos
* Rotacionar e deletar chaves de criptografia de segredos
* Recriptografar segredos

[CAUTION]
====
Não seguir o procedimento adequado para rotacionar chaves de criptografia de segredos pode deixar seu cluster permanentemente corrompido. Prossiga com cautela.
====

[#_encryption_key_rotation]
=== Rotação de Chaves de Criptografia de Segredos

[IMPORTANT]
.Gatilho de Versão
====
Disponível a partir das versões de setembro de 2024: v1.30.5+k3s1, v1.31.1+k3s1.
====

[tabs,sync-group-id=se]
======
Servidor Único::
+
--
Para rotacionar chaves de criptografia de segredos em um cluster de servidor único:

. Inicie o servidor K3s com a flag `--secrets-encryption`
+
[NOTE]
====
Iniciar o K3s sem criptografia e habilitá-la posteriormente não é atualmente suportado.
====

. Rotacionar chaves de criptografia de segredos
+
----
k3s secrets-encrypt rotate-keys
----

. Aguarde a recriptografia terminar. Observe os logs do servidor ou aguarde por:
+
[,bash]
----
$ k3s secrets-encrypt status
Encryption Status: Enabled
Current Rotation Stage: reencrypt_finished
----
--

Alta Disponibilidade::
+
--
Para rotacionar chaves de criptografia de segredos em configurações de alta disponibilidade:

. Inicie os três servidores K3s com a flag `--secrets-encryption`. Para brevidade, os servidores serão referidos como S1, S2, S3.
+
[NOTE]
====
Iniciar o K3s sem criptografia e habilitá-la posteriormente não é atualmente suportado.
====

. Rotacionar chaves de criptografia de segredos no S1
+
[,bash]
----
k3s secrets-encrypt rotate-keys
----

. Aguarde a recriptografar terminar. Observe os logs do servidor ou aguarde por:
+
[,bash]
----
$ k3s secrets-encrypt status
Encryption Status: Enabled
Current Rotation Stage: reencrypt_finished
----
+
[NOTE]
====
O K3s recriptografará ~5 segredos por segundo. Clusters com um grande número de segredos podem levar vários minutos para recriptografar. Você pode acompanhar o progresso nos logs do servidor.
====

. Reinicie o K3s no S1 com os mesmos argumentos. Se estiver executando o K3s como um serviço:
+
[,bash]
----
# If using systemd
systemctl restart k3s
# If using openrc
rc-service k3s restart
----

. Uma vez que o S1 esteja ativo, reinicie o K3s no S2 e S3
--
======

=== Rotação de Chaves de Criptografia Legadas

[TIP]
.Novo Procedimento
====
Se estiver usando versões do K3s v1.30+, recomendamos usar a xref:#_encryption_key_rotation[Rotação de Chaves de Criptografia de Segredos] em vez disso.
====

[tabs,sync-group-id=se]
======
Servidor Único::
+
--
Para rotacionar chaves de criptografia de segredos em um cluster de servidor único:

. Inicie o servidor K3s com a flag `--secrets-encryption`
+
[NOTE]
====
Iniciar o K3s sem criptografia e habilitá-la posteriormente não é atualmente suportado.
====

. Preparar
+
[,bash]
----
k3s secrets-encrypt prepare
----

. Matar e reiniciar o servidor K3s com os mesmos argumentos. Se estiver executando o K3s como um serviço:
+
[,bash]
----
# If using systemd
systemctl restart k3s
# If using openrc
rc-service k3s restart
----

. Rotacionar
+
[,bash]
----
k3s secrets-encrypt rotate
----

. Matar e reiniciar o servidor K3s com os mesmos argumentos
. Recriptografar
+
[NOTE]
====
O K3s recriptografará ~5 segredos por segundo. +
Clusters com um grande número de segredos podem levar vários minutos para recriptografar.
====
+
[,bash]
----
k3s secrets-encrypt reencrypt
----
--

Alta Disponibilidade::
+
--
Os passos são os mesmos para clusters de DB embutido e DB externo.

Para rotacionar chaves de criptografia de segredos em configurações de alta disponibilidade:

. Inicie os três servidores K3s com a flag `--secrets-encryption`. Para brevidade, os servidores serão referidos como S1, S2, S3.
+
[NOTE]
====
* Iniciar o K3s sem criptografia e habilitá-la posteriormente atualmente _não_ é suportado.
* Embora não seja obrigatório, é recomendado que você escolha um nó de servidor do qual executar os comandos `secrets-encrypt`.
====
. Preparar no S1
+
[,bash]
----
k3s secrets-encrypt prepare
----

. Matar e reiniciar o S1 com os mesmos argumentos. Se estiver executando o K3s como um serviço:
+
[,bash]
----
# If using systemd
systemctl restart k3s
# If using openrc
rc-service k3s restart
----

. Uma vez que o S1 esteja ativo, mate e reinicie o S2 e S3
. Rotacionar no S1
+
[,bash]
----
k3s secrets-encrypt rotate
----

. Matar e reiniciar o S1 com os mesmos argumentos
. Uma vez que o S1 esteja ativo, mate e reinicie o S2 e S3
. Recriptografar no S1
+
[NOTE]
====
O K3s recriptografará ~5 segredos por segundo. +
Clusters com um grande número de segredos podem levar vários minutos para recriptografar.
====
+
[,bash]
----
k3s secrets-encrypt reencrypt
----

. Matar e reiniciar o S1 com os mesmos argumentos
. Uma vez que o S1 esteja ativo, mate e reinicie o S2 e S3
--
======

=== Desativar/Reativar a Criptografia de Segredos

[tabs,sync-group-id=se]
======
Servidor Único::
+
--
Após iniciar um servidor com a flag `--secrets-encryption`, a criptografia de segredos pode ser desativada.

Para desativar a criptografia de segredos em um cluster de nó único:

. Desabilitar
+
[,bash]
----
k3s secrets-encrypt disable
----

. Finalizar e reiniciar o servidor K3s com os mesmos argumentos. Se estiver executando o K3s como um serviço:
+
[,bash]
----
# If using systemd
systemctl restart k3s
# If using openrc
rc-service k3s restart
----

. Recriptografar com flags
+
[,bash]
----
k3s secrets-encrypt reencrypt --force --skip
----

Para reativar a criptografia de segredos em um cluster de nó único:

. Ativar
+
[,bash]
----
k3s secrets-encrypt enable
----

. Matar e reiniciar o servidor K3s com os mesmos argumentos
. Recriptografar com flags
+
[,bash]
----
k3s secrets-encrypt reencrypt --force --skip
----
--

Alta Disponibilidade::
+
--
Após iniciar um cluster de alta disponibilidade com as flags `--secrets-encryption`, a criptografia de segredos pode ser desativada.

[NOTE]
====
Embora não seja obrigatório, é recomendado que você escolha um nó de servidor do qual executar os comandos `secrets-encrypt`.
====

Para brevidade, os três servidores usados neste guia serão referidos como S1, S2, S3.

Para desativar a criptografia de segredos em um cluster de alta disponibilidade:

. Desativar no S1
+
[,bash]
----
k3s secrets-encrypt disable
----

. Matar e reiniciar o S1 com os mesmos argumentos. Se estiver executando o K3s como um serviço:
+
[,bash]
----
# If using systemd
systemctl restart k3s
# If using openrc
rc-service k3s restart
----

. Uma vez que o S1 esteja ativo, mate e reinicie o S2 e S3
. Recriptografar com flags no S1
+
[,bash]
----
k3s secrets-encrypt reencrypt --force --skip
----

Para reativar a criptografia de segredos em um cluster de alta disponibilidade:

. Habilitar no S1
+
[,bash]
----
k3s secrets-encrypt enable
----

. Matar e reiniciar o S1 com os mesmos argumentos
. Uma vez que o S1 esteja ativo, mate e reinicie o S2 e S3
. Recriptografar com flags no S1
+
[,bash]
----
k3s secrets-encrypt reencrypt --force --skip
----
--
======

=== Status da Criptografia de Segredos

A ferramenta secrets-encrypt inclui um comando `status` que exibe informações sobre o status atual da criptografia de segredos no nó.

Um exemplo do comando em um nó de servidor único:

[,bash]
----
$ k3s secrets-encrypt status
Encryption Status: Enabled
Current Rotation Stage: start
Server Encryption Hashes: All hashes match

Active  Key Type  Name
------  --------  ----
 *      AES-CBC   aescbckey
----

Outro exemplo em cluster HA, após a rotação das chaves, mas antes de reiniciar os servidores:

[,bash]
----
$ k3s secrets-encrypt status
Encryption Status: Enabled
Current Rotation Stage: rotate
Server Encryption Hashes: hash does not match between node-1 and node-2

Active  Key Type  Name
------  --------  ----
 *      AES-CBC   aescbckey-2021-12-10T22:54:38Z
        AES-CBC   aescbckey
----

Os detalhes de cada seção são os seguintes:

* *Estado de Criptografia*: Exibido se a criptografia de segredos está desativada ou ativada no nó.
* *Estágio Atual de Rotação*: Indica o estágio atual de rotação no nó. +
Os estágios são: `start`, `prepare`, `rotate`, `reencrypt_request`, `reencrypt_active`, `reencrypt_finished`
* *Hashes de Criptografia do Servidor*: Útil para clusters HA, isso indica se todos os servidores estão no mesmo estágio com seus arquivos locais. Isso pode ser usado para identificar se é necessário reiniciar os servidores antes de prosseguir para o próximo estágio. No exemplo HA acima, o nó-1 e o nó-2 têm hashes diferentes, indicando que atualmente não possuem a mesma configuração de criptografia. Reiniciar os servidores sincronizará sua configuração.
* *Tabela de Chaves*: Resume informações sobre as chaves de criptografia de segredos encontradas no nó.
 ** *Ativo*: O "*" indica quais, se houver, as chaves estão atualmente sendo usadas para a criptografia de segredos. Uma chave ativa é usada pelo Kubernetes para criptografar quaisquer novos segredos.
 ** *Tipo de Chave*: Todas as chaves que usam esta ferramenta são do tipo `AES-CBC`. Veja mais informações https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/#providers[aqui.]
 ** *Nome*: Nome da chave de criptografia.
