= シークレット暗号化設定
:page-languages: [en, ja, ko, zh]
:revdate: 2026-03-03
:page-revdate: {revdate}

K3sは、静止状態でのシークレット暗号化を有効にすることをサポートしています。サーバーを最初に起動する際に、フラグ`--secrets-encryption`を渡すと、次のことが自動的に行われます：

* AES-CBCキーを生成します。
* 生成されたキーを使用して暗号化設定ファイルを生成します。
* 設定をKubeAPIに暗号化プロバイダ設定として渡します。

[TIP]
====
既存のサーバーでは、再起動せずにシークレット暗号化を有効にすることはできません。 +
スクリプトからインストールする場合は`curl -sfL https://get.k3s.io | INSTALL_K3S_ARTIFACT_URL=<PRIME-ARTIFACTS-URL>/k3s sh -s - server --secrets-encryption`を使用するか、xref:installation/configuration.adoc#_configuration_with_install_script[設定オプション]に記載されている他の方法を使用してください。
====

== 暗号化プロバイダの選択

[IMPORTANT]
.バージョンゲート
====
2025年4月のリリースから利用可能：v1.30.12+k3s1、v1.31.8+k3s1、v1.32.4+k3s1、v1.33.0+k3s1。
====

`--secrets-encryption-provider`フラグを使用すると、次のK3sサポートの暗号化プロバイダから選択できます：

* `aescbc`:PKCS#7パディングを使用したAES-CBC。これはデフォルトのプロバイダです。
* `secretbox`:XSalsa20およびPoly1305

### プロバイダの移行

`aescbc`プロバイダから`secretbox`プロバイダに移行するには、次の手順に従ってください：

. `secretbox`プロバイダがあなたのK3sバージョンでサポートされていることを確認してください。
. K3s設定ファイルに`secrets-encryption-provider`フラグを`secretbox`に更新/追加します。
. 以下のxref:cli/secrets-encrypt.adoc#_encryption_key_rotation[暗号化キーのローテーション]セクションに従って、暗号化キーをローテーションします。

== 生成された暗号化設定ファイル

`--secrets-encryption`を使用してサーバーを起動すると、K3sは`/var/lib/rancher/k3s/server/cred/encryption-config.json`に暗号化設定ファイルを生成します。

以下は、デフォルトの`aescbc`プロバイダを使用した生成された暗号化設定ファイルの例です：

[,json]
----
{
  "kind": "EncryptionConfiguration",
  "apiVersion": "apiserver.config.k8s.io/v1",
  "resources": [
    {
      "resources": [
        "secrets"
      ],
      "providers": [
        {
          "aescbc": {
            "keys": [
              {
                "name": "aescbckey",
                "secret": "xxxxxxxxxxxxxxxxxxx"
              }
            ]
          }
        },
        {
          "identity": {}
        }
      ]
    }
  ]
}
----

== シークレット暗号化ツール

K3sには、以下の自動制御を可能にするユーティリティツール`secrets-encrypt`が含まれています：

* シークレット暗号化の無効化/有効化
* 新しい暗号化キーの追加
* 暗号化キーのローテーションと削除
* シークレットの再暗号化

詳細については、xref:cli/secrets-encrypt.adoc[`k3s secrets-encrypt`コマンドのドキュメント]を参照してください。
