= Flag-Auslauf
:page-languages: [en, ja, ko, zh]
:revdate: 2024-09-09
:page-revdate: {revdate}

K3s ist ein schnelllebiges Projekt, und daher benötigen wir eine Möglichkeit, Flags und Konfigurationsoptionen auslaufen zu lassen. Diese Seite beschreibt den Prozess für das Auslaufen von Flags und Konfigurationsoptionen. Um sicherzustellen, dass die Benutzer nicht von der Entfernung von Flags überrascht werden, ähnelt der Prozess der https://kubernetes.io/docs/reference/using-api/deprecation-policy/[Kubernetes-Auslaufrichtlinie].

== Vorgang

. Flags können jederzeit als "Zum Auslaufen vorgesehen" gekennzeichnet werden.
. Flags, die als "Zum Auslaufen vorgesehen" gekennzeichnet sind, müssen im nächsten Patch aller derzeit unterstützten Versionen entsprechend markiert werden. Darüber hinaus wird das Flag beginnen, die Benutzer zu warnen, dass es in der nächsten Minor-Version auslaufen wird.
. In der nächsten Minor-Version wird ein Flag in der Dokumentation als auslaufend gekennzeichnet und im Code in ein verstecktes Flag umgewandelt. Das Flag wird weiterhin funktionieren und die Benutzer warnen.
. In der folgenden Minor-Version werden auslaufende Flags "nicht funktionsfähig" und verursachen einen fatalen Fehler, wenn sie verwendet werden. Dieser Fehler muss dem Benutzer alle neuen Flags oder Konfigurationen erklären, die dieses Flag ersetzen.
. In der nächsten Minor-Version werden die nicht funktionsfähigen Flags aus der Dokumentation und dem Code entfernt.

== Beispiel

Ein Beispiel für den Prozess:

* `--foo` existiert in v1.22.14, v1.23.10 und v1.24.2.
* Nach der Veröffentlichung von v1.24.2 wird beschlossen, `--foo` zugunsten von `--new-foo` auslaufen zu lassen.
* In v1.22.15, v1.23.11 und v1.24.3 existiert `--foo` weiterhin, wird jedoch die Benutzer warnen:
+
----
[Warning] --foo will be deprecated in v1.25.0, use `--new-foo` instead
----
+
`--foo` wird als funktionsfähiges Flag für die Dauer von v1.22, v1.23 und v1.24 weiterhin existieren.

* In v1.25.0 wird `--foo` in der Dokumentation als auslaufend gekennzeichnet und im Code verborgen. Es wird weiterhin funktionieren und die Benutzer warnen, zu `--new-foo` zu wechseln.
* In v1.26.0 wird `--foo` einen fatalen Fehler verursachen, wenn es verwendet wird. Die Fehlermeldung wird sagen:
+
----
[Fatal] exit 1: --foo is no longer supported, use --new-foo instead
----

* In v1.27.0 wird `--foo` vollständig aus dem gesamten Code und der gesamten Dokumentation entfernt.
